// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern ap_fixed<30, 3, (ap_q_mode) 4, (ap_o_mode)0, 0> Compult ( ap_fixed<32, 3, (ap_q_mode) 4, (ap_o_mode)0, 0> y_in,  ap_fixed<30, 3, (ap_q_mode) 4, (ap_o_mode)0, 0> ref_in);

