// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "Compult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Compult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Compult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> Compult::ap_ST_st1_fsm_0 = "1";
const sc_lv<12> Compult::ap_ST_st2_fsm_1 = "10";
const sc_lv<12> Compult::ap_ST_st3_fsm_2 = "100";
const sc_lv<12> Compult::ap_ST_st4_fsm_3 = "1000";
const sc_lv<12> Compult::ap_ST_st5_fsm_4 = "10000";
const sc_lv<12> Compult::ap_ST_st6_fsm_5 = "100000";
const sc_lv<12> Compult::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<12> Compult::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<12> Compult::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<12> Compult::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<12> Compult::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<12> Compult::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<32> Compult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Compult::ap_const_lv1_1 = "1";
const sc_lv<32> Compult::ap_const_lv32_1 = "1";
const sc_lv<32> Compult::ap_const_lv32_2 = "10";
const sc_lv<32> Compult::ap_const_lv32_3 = "11";
const sc_lv<32> Compult::ap_const_lv32_5 = "101";
const sc_lv<32> Compult::ap_const_lv32_6 = "110";
const sc_lv<32> Compult::ap_const_lv32_7 = "111";
const sc_lv<32> Compult::ap_const_lv32_8 = "1000";
const sc_lv<32> Compult::ap_const_lv32_9 = "1001";
const sc_lv<32> Compult::ap_const_lv32_A = "1010";
const sc_lv<32> Compult::ap_const_lv32_B = "1011";
const sc_lv<32> Compult::ap_const_lv32_1F = "11111";
const sc_lv<32> Compult::ap_const_lv32_1D = "11101";
const sc_lv<30> Compult::ap_const_lv30_1FFFFFFF = "11111111111111111111111111111";
const sc_lv<32> Compult::ap_const_lv32_1E = "11110";
const sc_lv<30> Compult::ap_const_lv30_20000000 = "100000000000000000000000000000";
const sc_lv<2> Compult::ap_const_lv2_0 = "00";
const sc_lv<42> Compult::ap_const_lv42_1F4 = "111110100";
const sc_lv<32> Compult::ap_const_lv32_29 = "101001";
const sc_lv<32> Compult::ap_const_lv32_21 = "100001";
const sc_lv<32> Compult::ap_const_lv32_22 = "100010";
const sc_lv<8> Compult::ap_const_lv8_FF = "11111111";
const sc_lv<8> Compult::ap_const_lv8_0 = "00000000";
const sc_lv<32> Compult::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> Compult::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<32> Compult::ap_const_lv32_20 = "100000";
const sc_lv<3> Compult::ap_const_lv3_0 = "000";
const sc_lv<3> Compult::ap_const_lv3_7 = "111";

Compult::Compult(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_Compult_mpc_pso_fu_113 = new Compult_mpc_pso("grp_Compult_mpc_pso_fu_113");
    grp_Compult_mpc_pso_fu_113->ap_clk(ap_clk);
    grp_Compult_mpc_pso_fu_113->ap_rst(ap_rst);
    grp_Compult_mpc_pso_fu_113->ap_start(grp_Compult_mpc_pso_fu_113_ap_start);
    grp_Compult_mpc_pso_fu_113->ap_done(grp_Compult_mpc_pso_fu_113_ap_done);
    grp_Compult_mpc_pso_fu_113->ap_idle(grp_Compult_mpc_pso_fu_113_ap_idle);
    grp_Compult_mpc_pso_fu_113->ap_ready(grp_Compult_mpc_pso_fu_113_ap_ready);
    grp_Compult_mpc_pso_fu_113->dx1_in_V(grp_Compult_mpc_pso_fu_113_dx1_in_V);
    grp_Compult_mpc_pso_fu_113->dx2_in_V(grp_Compult_mpc_pso_fu_113_dx2_in_V);
    grp_Compult_mpc_pso_fu_113->y_in_V(grp_Compult_mpc_pso_fu_113_y_in_V);
    grp_Compult_mpc_pso_fu_113->u_in_V(grp_Compult_mpc_pso_fu_113_u_in_V);
    grp_Compult_mpc_pso_fu_113->ref_in_V(grp_Compult_mpc_pso_fu_113_ref_in_V);
    grp_Compult_mpc_pso_fu_113->ap_return(grp_Compult_mpc_pso_fu_113_ap_return);
    Compult_mul_32s_10ns_42_3_U59 = new Compult_mul_32s_10ns_42_3<1,3,32,10,42>("Compult_mul_32s_10ns_42_3_U59");
    Compult_mul_32s_10ns_42_3_U59->clk(ap_clk);
    Compult_mul_32s_10ns_42_3_U59->reset(ap_rst);
    Compult_mul_32s_10ns_42_3_U59->din0(grp_fu_320_p0);
    Compult_mul_32s_10ns_42_3_U59->din1(grp_fu_320_p1);
    Compult_mul_32s_10ns_42_3_U59->ce(grp_fu_320_ce);
    Compult_mul_32s_10ns_42_3_U59->dout(grp_fu_320_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Range1_all_ones_fu_382_p2);
    sensitive << ( p_Result_20_i_reg_777 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_return);
    sensitive << ( du_V_reg_840 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_sig_bdd_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_123);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_145);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_225);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_80);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_91);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_158 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_225 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_28 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_71 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_80 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_91 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_110 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_123 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_132 );

    SC_METHOD(thread_brmerge2_i_fu_572_p2);
    sensitive << ( overflow_5_reg_811 );
    sensitive << ( underflow_16_not_i_fu_567_p2 );

    SC_METHOD(thread_brmerge39_i_i_fu_546_p2);
    sensitive << ( p_not38_i_i_fu_540_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_534_p2 );

    SC_METHOD(thread_brmerge40_demorgan_i_i_fu_397_p2);
    sensitive << ( newsignbit_4_reg_761 );
    sensitive << ( Range1_all_ones_fu_382_p2 );

    SC_METHOD(thread_brmerge_fu_667_p2);
    sensitive << ( newsignbit_6_reg_858 );
    sensitive << ( isneg_not_fu_662_p2 );

    SC_METHOD(thread_brmerge_i6_fu_282_p2);
    sensitive << ( newsignbit_reg_728 );
    sensitive << ( isneg_not_i_fu_277_p2 );

    SC_METHOD(thread_brmerge_i6_i_fu_516_p2);
    sensitive << ( newsignbit_5_fu_492_p3 );
    sensitive << ( p_not_i5_i_fu_510_p2 );

    SC_METHOD(thread_brmerge_i_i2_fu_392_p2);
    sensitive << ( newsignbit_4_reg_761 );
    sensitive << ( p_not_i_i_fu_387_p2 );

    SC_METHOD(thread_brmerge_i_i5_i_fu_563_p2);
    sensitive << ( overflow_5_reg_811 );
    sensitive << ( underflow_4_reg_817 );

    SC_METHOD(thread_brmerge_i_i_fu_658_p2);
    sensitive << ( isneg_3_reg_845 );
    sensitive << ( newsignbit_6_reg_858 );

    SC_METHOD(thread_brmerge_i_i_i3_fu_428_p2);
    sensitive << ( underflow_3_fu_423_p2 );
    sensitive << ( overflow_4_fu_413_p2 );

    SC_METHOD(thread_brmerge_i_i_i_fu_273_p2);
    sensitive << ( isneg_reg_715 );
    sensitive << ( newsignbit_reg_728 );

    SC_METHOD(thread_du_V_fu_604_p3);
    sensitive << ( grp_Compult_mpc_pso_fu_113_ap_return );

    SC_METHOD(thread_dx1_V_fu_309_p3);
    sensitive << ( tmp_21_reg_735 );

    SC_METHOD(thread_dx2_V_fu_590_p3);
    sensitive << ( brmerge2_i_fu_572_p2 );
    sensitive << ( p_Val2_101_mux_i_fu_577_p3 );
    sensitive << ( p_Val2_3_i_fu_584_p3 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_ap_start);
    sensitive << ( grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_dx1_in_V);
    sensitive << ( dx1_V_reg_740 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_dx2_in_V);
    sensitive << ( dx2_V_reg_829 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_ref_in_V);
    sensitive << ( ref_in_V );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_u_in_V);
    sensitive << ( u_V );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_113_y_in_V);
    sensitive << ( p_Val2_20_reg_710 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_fu_320_ce);

    SC_METHOD(thread_grp_fu_320_p0);
    sensitive << ( dx1_V_fu_309_p3 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_fu_320_p1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_isneg_2_fu_480_p3);
    sensitive << ( p_Val2_28_fu_474_p2 );

    SC_METHOD(thread_isneg_not_fu_662_p2);
    sensitive << ( isneg_3_reg_845 );

    SC_METHOD(thread_isneg_not_i_fu_277_p2);
    sensitive << ( isneg_reg_715 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_534_p2);
    sensitive << ( newsignbit_5_fu_492_p3 );

    SC_METHOD(thread_newsignbit_5_fu_492_p3);
    sensitive << ( p_Val2_28_fu_474_p2 );

    SC_METHOD(thread_overflow_4_fu_413_p2);
    sensitive << ( brmerge_i_i2_reg_788 );
    sensitive << ( tmp_34_i_fu_408_p2 );

    SC_METHOD(thread_overflow_5_fu_528_p2);
    sensitive << ( brmerge_i6_i_fu_516_p2 );
    sensitive << ( tmp_37_i6_fu_522_p2 );

    SC_METHOD(thread_overflow_fu_207_p2);
    sensitive << ( tmp_51_fu_193_p3 );
    sensitive << ( tmp_15_fu_201_p2 );

    SC_METHOD(thread_p_Result_21_i_fu_500_p4);
    sensitive << ( p_Val2_28_fu_474_p2 );

    SC_METHOD(thread_p_Val2_101_mux_i_fu_577_p3);
    sensitive << ( p_Val2_29_reg_805 );
    sensitive << ( brmerge_i_i5_i_fu_563_p2 );

    SC_METHOD(thread_p_Val2_108_mux_fu_672_p3);
    sensitive << ( p_Val2_34_reg_852 );
    sensitive << ( brmerge_i_i_fu_658_p2 );

    SC_METHOD(thread_p_Val2_19_fu_187_p2);
    sensitive << ( p_Val2_s_fu_141_p4 );
    sensitive << ( tmp_s_fu_183_p1 );

    SC_METHOD(thread_p_Val2_20_fu_213_p3);
    sensitive << ( p_Val2_19_reg_700 );
    sensitive << ( overflow_reg_705 );

    SC_METHOD(thread_p_Val2_22_fu_231_p2);
    sensitive << ( tmp_i_fu_219_p1 );
    sensitive << ( tmp_i_41_fu_227_p1 );

    SC_METHOD(thread_p_Val2_23_fu_245_p1);
    sensitive << ( p_Val2_22_fu_231_p2 );

    SC_METHOD(thread_p_Val2_25_fu_402_p3);
    sensitive << ( tmp_16_reg_772 );
    sensitive << ( qb_assign_8_reg_783 );

    SC_METHOD(thread_p_Val2_26_fu_455_p3);
    sensitive << ( tmp7_fu_434_p2 );
    sensitive << ( p_Val2_97_mux_i_fu_439_p3 );
    sensitive << ( p_Val2_i4_fu_447_p3 );

    SC_METHOD(thread_p_Val2_28_fu_474_p2);
    sensitive << ( tmp_35_i_fu_463_p1 );
    sensitive << ( tmp_36_i5_fu_470_p1 );

    SC_METHOD(thread_p_Val2_29_fu_488_p1);
    sensitive << ( p_Val2_28_fu_474_p2 );

    SC_METHOD(thread_p_Val2_33_fu_619_p2);
    sensitive << ( tmp_17_fu_612_p1 );
    sensitive << ( tmp_18_fu_615_p1 );

    SC_METHOD(thread_p_Val2_34_fu_633_p1);
    sensitive << ( p_Val2_33_fu_619_p2 );

    SC_METHOD(thread_p_Val2_3_i_fu_584_p3);
    sensitive << ( p_Val2_29_reg_805 );
    sensitive << ( underflow_4_reg_817 );

    SC_METHOD(thread_p_Val2_94_mux_i_fu_287_p3);
    sensitive << ( p_Val2_23_reg_722 );
    sensitive << ( brmerge_i_i_i_fu_273_p2 );

    SC_METHOD(thread_p_Val2_97_mux_i_fu_439_p3);
    sensitive << ( brmerge_i_i_i3_fu_428_p2 );
    sensitive << ( p_Val2_25_fu_402_p3 );

    SC_METHOD(thread_p_Val2_i4_fu_447_p3);
    sensitive << ( underflow_3_fu_423_p2 );
    sensitive << ( p_Val2_25_fu_402_p3 );

    SC_METHOD(thread_p_Val2_i_fu_294_p3);
    sensitive << ( p_Val2_23_reg_722 );
    sensitive << ( underflow_fu_268_p2 );

    SC_METHOD(thread_p_Val2_s_42_fu_679_p3);
    sensitive << ( p_Val2_34_reg_852 );
    sensitive << ( underflow_5_fu_653_p2 );

    SC_METHOD(thread_p_Val2_s_fu_141_p4);
    sensitive << ( y_in_V );

    SC_METHOD(thread_p_not38_i_i_fu_540_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( p_Result_21_i_fu_500_p4 );

    SC_METHOD(thread_p_not_i5_i_fu_510_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( p_Result_21_i_fu_500_p4 );

    SC_METHOD(thread_p_not_i_i_fu_387_p2);
    sensitive << ( p_Result_20_i_reg_777 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_qb_assign_6_fu_177_p2);
    sensitive << ( r_i_i_fu_171_p2 );
    sensitive << ( qbit_fu_151_p3 );

    SC_METHOD(thread_qb_assign_8_fu_378_p2);
    sensitive << ( qbit_3_reg_756 );
    sensitive << ( tmp_58_reg_767 );

    SC_METHOD(thread_qbit_fu_151_p3);
    sensitive << ( y_in_V );

    SC_METHOD(thread_r_fu_159_p1);
    sensitive << ( y_in_V );

    SC_METHOD(thread_r_i_i_fu_171_p2);
    sensitive << ( tmp_50_fu_163_p3 );
    sensitive << ( r_fu_159_p1 );

    SC_METHOD(thread_tmp7_fu_434_p2);
    sensitive << ( brmerge40_demorgan_i_i_reg_793 );
    sensitive << ( tmp_34_i_fu_408_p2 );

    SC_METHOD(thread_tmp_15_fu_201_p2);
    sensitive << ( tmp_47_fu_133_p3 );

    SC_METHOD(thread_tmp_17_fu_612_p1);
    sensitive << ( u_V );

    SC_METHOD(thread_tmp_18_fu_615_p1);
    sensitive << ( du_V_fu_604_p3 );

    SC_METHOD(thread_tmp_19_fu_648_p2);
    sensitive << ( newsignbit_6_reg_858 );

    SC_METHOD(thread_tmp_20_fu_686_p3);
    sensitive << ( brmerge_fu_667_p2 );
    sensitive << ( p_Val2_108_mux_fu_672_p3 );
    sensitive << ( p_Val2_s_42_fu_679_p3 );

    SC_METHOD(thread_tmp_21_fu_301_p3);
    sensitive << ( brmerge_i6_fu_282_p2 );
    sensitive << ( p_Val2_94_mux_i_fu_287_p3 );
    sensitive << ( p_Val2_i_fu_294_p3 );

    SC_METHOD(thread_tmp_34_i_fu_408_p2);
    sensitive << ( signbit_reg_750 );

    SC_METHOD(thread_tmp_35_i_fu_463_p1);
    sensitive << ( p_Val2_26_reg_799 );

    SC_METHOD(thread_tmp_36_i5_fu_470_p1);
    sensitive << ( x2_2_V );

    SC_METHOD(thread_tmp_36_i_fu_263_p2);
    sensitive << ( newsignbit_reg_728 );

    SC_METHOD(thread_tmp_37_i6_fu_522_p2);
    sensitive << ( isneg_2_fu_480_p3 );

    SC_METHOD(thread_tmp_47_fu_133_p3);
    sensitive << ( y_in_V );

    SC_METHOD(thread_tmp_50_fu_163_p3);
    sensitive << ( y_in_V );

    SC_METHOD(thread_tmp_51_fu_193_p3);
    sensitive << ( p_Val2_19_fu_187_p2 );

    SC_METHOD(thread_tmp_fu_418_p2);
    sensitive << ( brmerge40_demorgan_i_i_reg_793 );

    SC_METHOD(thread_tmp_i_41_fu_227_p1);
    sensitive << ( x1_1_V );

    SC_METHOD(thread_tmp_i_fu_219_p1);
    sensitive << ( p_Val2_20_fu_213_p3 );

    SC_METHOD(thread_tmp_s_fu_183_p1);
    sensitive << ( qb_assign_6_fu_177_p2 );

    SC_METHOD(thread_underflow_16_not_i_fu_567_p2);
    sensitive << ( underflow_4_reg_817 );

    SC_METHOD(thread_underflow_3_fu_423_p2);
    sensitive << ( signbit_reg_750 );
    sensitive << ( tmp_fu_418_p2 );

    SC_METHOD(thread_underflow_4_fu_552_p2);
    sensitive << ( isneg_2_fu_480_p3 );
    sensitive << ( brmerge39_i_i_fu_546_p2 );

    SC_METHOD(thread_underflow_5_fu_653_p2);
    sensitive << ( isneg_3_reg_845 );
    sensitive << ( tmp_19_fu_648_p2 );

    SC_METHOD(thread_underflow_fu_268_p2);
    sensitive << ( isneg_reg_715 );
    sensitive << ( tmp_36_i_fu_263_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_Compult_mpc_pso_fu_113_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000001";
    x1_1_V = "000000000000000000000000000000";
    x2_2_V = "00000000000000000000000000000000";
    u_V = "000000000000000000000000000000";
    grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Compult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, y_in_V, "(port)y_in_V");
    sc_trace(mVcdFile, ref_in_V, "(port)ref_in_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_28, "ap_sig_bdd_28");
    sc_trace(mVcdFile, x1_1_V, "x1_1_V");
    sc_trace(mVcdFile, x2_2_V, "x2_2_V");
    sc_trace(mVcdFile, u_V, "u_V");
    sc_trace(mVcdFile, p_Val2_19_fu_187_p2, "p_Val2_19_fu_187_p2");
    sc_trace(mVcdFile, p_Val2_19_reg_700, "p_Val2_19_reg_700");
    sc_trace(mVcdFile, overflow_fu_207_p2, "overflow_fu_207_p2");
    sc_trace(mVcdFile, overflow_reg_705, "overflow_reg_705");
    sc_trace(mVcdFile, p_Val2_20_fu_213_p3, "p_Val2_20_fu_213_p3");
    sc_trace(mVcdFile, p_Val2_20_reg_710, "p_Val2_20_reg_710");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_56, "ap_sig_bdd_56");
    sc_trace(mVcdFile, isneg_reg_715, "isneg_reg_715");
    sc_trace(mVcdFile, p_Val2_23_fu_245_p1, "p_Val2_23_fu_245_p1");
    sc_trace(mVcdFile, p_Val2_23_reg_722, "p_Val2_23_reg_722");
    sc_trace(mVcdFile, newsignbit_reg_728, "newsignbit_reg_728");
    sc_trace(mVcdFile, tmp_21_fu_301_p3, "tmp_21_fu_301_p3");
    sc_trace(mVcdFile, tmp_21_reg_735, "tmp_21_reg_735");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_71, "ap_sig_bdd_71");
    sc_trace(mVcdFile, dx1_V_fu_309_p3, "dx1_V_fu_309_p3");
    sc_trace(mVcdFile, dx1_V_reg_740, "dx1_V_reg_740");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_80, "ap_sig_bdd_80");
    sc_trace(mVcdFile, signbit_reg_750, "signbit_reg_750");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_91, "ap_sig_bdd_91");
    sc_trace(mVcdFile, qbit_3_reg_756, "qbit_3_reg_756");
    sc_trace(mVcdFile, newsignbit_4_reg_761, "newsignbit_4_reg_761");
    sc_trace(mVcdFile, tmp_58_reg_767, "tmp_58_reg_767");
    sc_trace(mVcdFile, tmp_16_reg_772, "tmp_16_reg_772");
    sc_trace(mVcdFile, p_Result_20_i_reg_777, "p_Result_20_i_reg_777");
    sc_trace(mVcdFile, qb_assign_8_fu_378_p2, "qb_assign_8_fu_378_p2");
    sc_trace(mVcdFile, qb_assign_8_reg_783, "qb_assign_8_reg_783");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_110, "ap_sig_bdd_110");
    sc_trace(mVcdFile, brmerge_i_i2_fu_392_p2, "brmerge_i_i2_fu_392_p2");
    sc_trace(mVcdFile, brmerge_i_i2_reg_788, "brmerge_i_i2_reg_788");
    sc_trace(mVcdFile, brmerge40_demorgan_i_i_fu_397_p2, "brmerge40_demorgan_i_i_fu_397_p2");
    sc_trace(mVcdFile, brmerge40_demorgan_i_i_reg_793, "brmerge40_demorgan_i_i_reg_793");
    sc_trace(mVcdFile, p_Val2_26_fu_455_p3, "p_Val2_26_fu_455_p3");
    sc_trace(mVcdFile, p_Val2_26_reg_799, "p_Val2_26_reg_799");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_123, "ap_sig_bdd_123");
    sc_trace(mVcdFile, p_Val2_29_fu_488_p1, "p_Val2_29_fu_488_p1");
    sc_trace(mVcdFile, p_Val2_29_reg_805, "p_Val2_29_reg_805");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, overflow_5_fu_528_p2, "overflow_5_fu_528_p2");
    sc_trace(mVcdFile, overflow_5_reg_811, "overflow_5_reg_811");
    sc_trace(mVcdFile, underflow_4_fu_552_p2, "underflow_4_fu_552_p2");
    sc_trace(mVcdFile, underflow_4_reg_817, "underflow_4_reg_817");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_145, "ap_sig_bdd_145");
    sc_trace(mVcdFile, dx2_V_fu_590_p3, "dx2_V_fu_590_p3");
    sc_trace(mVcdFile, dx2_V_reg_829, "dx2_V_reg_829");
    sc_trace(mVcdFile, du_V_fu_604_p3, "du_V_fu_604_p3");
    sc_trace(mVcdFile, du_V_reg_840, "du_V_reg_840");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_158, "ap_sig_bdd_158");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_done, "grp_Compult_mpc_pso_fu_113_ap_done");
    sc_trace(mVcdFile, isneg_3_reg_845, "isneg_3_reg_845");
    sc_trace(mVcdFile, p_Val2_34_fu_633_p1, "p_Val2_34_fu_633_p1");
    sc_trace(mVcdFile, p_Val2_34_reg_852, "p_Val2_34_reg_852");
    sc_trace(mVcdFile, newsignbit_6_reg_858, "newsignbit_6_reg_858");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_start, "grp_Compult_mpc_pso_fu_113_ap_start");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_idle, "grp_Compult_mpc_pso_fu_113_ap_idle");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_ready, "grp_Compult_mpc_pso_fu_113_ap_ready");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_dx1_in_V, "grp_Compult_mpc_pso_fu_113_dx1_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_dx2_in_V, "grp_Compult_mpc_pso_fu_113_dx2_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_y_in_V, "grp_Compult_mpc_pso_fu_113_y_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_u_in_V, "grp_Compult_mpc_pso_fu_113_u_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ref_in_V, "grp_Compult_mpc_pso_fu_113_ref_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_return, "grp_Compult_mpc_pso_fu_113_ap_return");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg, "grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_20_fu_686_p3, "tmp_20_fu_686_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_225, "ap_sig_bdd_225");
    sc_trace(mVcdFile, tmp_50_fu_163_p3, "tmp_50_fu_163_p3");
    sc_trace(mVcdFile, r_fu_159_p1, "r_fu_159_p1");
    sc_trace(mVcdFile, r_i_i_fu_171_p2, "r_i_i_fu_171_p2");
    sc_trace(mVcdFile, qbit_fu_151_p3, "qbit_fu_151_p3");
    sc_trace(mVcdFile, qb_assign_6_fu_177_p2, "qb_assign_6_fu_177_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_141_p4, "p_Val2_s_fu_141_p4");
    sc_trace(mVcdFile, tmp_s_fu_183_p1, "tmp_s_fu_183_p1");
    sc_trace(mVcdFile, tmp_47_fu_133_p3, "tmp_47_fu_133_p3");
    sc_trace(mVcdFile, tmp_51_fu_193_p3, "tmp_51_fu_193_p3");
    sc_trace(mVcdFile, tmp_15_fu_201_p2, "tmp_15_fu_201_p2");
    sc_trace(mVcdFile, tmp_i_fu_219_p1, "tmp_i_fu_219_p1");
    sc_trace(mVcdFile, tmp_i_41_fu_227_p1, "tmp_i_41_fu_227_p1");
    sc_trace(mVcdFile, p_Val2_22_fu_231_p2, "p_Val2_22_fu_231_p2");
    sc_trace(mVcdFile, tmp_36_i_fu_263_p2, "tmp_36_i_fu_263_p2");
    sc_trace(mVcdFile, isneg_not_i_fu_277_p2, "isneg_not_i_fu_277_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_273_p2, "brmerge_i_i_i_fu_273_p2");
    sc_trace(mVcdFile, underflow_fu_268_p2, "underflow_fu_268_p2");
    sc_trace(mVcdFile, brmerge_i6_fu_282_p2, "brmerge_i6_fu_282_p2");
    sc_trace(mVcdFile, p_Val2_94_mux_i_fu_287_p3, "p_Val2_94_mux_i_fu_287_p3");
    sc_trace(mVcdFile, p_Val2_i_fu_294_p3, "p_Val2_i_fu_294_p3");
    sc_trace(mVcdFile, grp_fu_320_p0, "grp_fu_320_p0");
    sc_trace(mVcdFile, grp_fu_320_p1, "grp_fu_320_p1");
    sc_trace(mVcdFile, grp_fu_320_p2, "grp_fu_320_p2");
    sc_trace(mVcdFile, p_not_i_i_fu_387_p2, "p_not_i_i_fu_387_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_382_p2, "Range1_all_ones_fu_382_p2");
    sc_trace(mVcdFile, tmp_34_i_fu_408_p2, "tmp_34_i_fu_408_p2");
    sc_trace(mVcdFile, tmp_fu_418_p2, "tmp_fu_418_p2");
    sc_trace(mVcdFile, underflow_3_fu_423_p2, "underflow_3_fu_423_p2");
    sc_trace(mVcdFile, overflow_4_fu_413_p2, "overflow_4_fu_413_p2");
    sc_trace(mVcdFile, brmerge_i_i_i3_fu_428_p2, "brmerge_i_i_i3_fu_428_p2");
    sc_trace(mVcdFile, p_Val2_25_fu_402_p3, "p_Val2_25_fu_402_p3");
    sc_trace(mVcdFile, tmp7_fu_434_p2, "tmp7_fu_434_p2");
    sc_trace(mVcdFile, p_Val2_97_mux_i_fu_439_p3, "p_Val2_97_mux_i_fu_439_p3");
    sc_trace(mVcdFile, p_Val2_i4_fu_447_p3, "p_Val2_i4_fu_447_p3");
    sc_trace(mVcdFile, tmp_35_i_fu_463_p1, "tmp_35_i_fu_463_p1");
    sc_trace(mVcdFile, tmp_36_i5_fu_470_p1, "tmp_36_i5_fu_470_p1");
    sc_trace(mVcdFile, p_Val2_28_fu_474_p2, "p_Val2_28_fu_474_p2");
    sc_trace(mVcdFile, p_Result_21_i_fu_500_p4, "p_Result_21_i_fu_500_p4");
    sc_trace(mVcdFile, newsignbit_5_fu_492_p3, "newsignbit_5_fu_492_p3");
    sc_trace(mVcdFile, p_not_i5_i_fu_510_p2, "p_not_i5_i_fu_510_p2");
    sc_trace(mVcdFile, isneg_2_fu_480_p3, "isneg_2_fu_480_p3");
    sc_trace(mVcdFile, brmerge_i6_i_fu_516_p2, "brmerge_i6_i_fu_516_p2");
    sc_trace(mVcdFile, tmp_37_i6_fu_522_p2, "tmp_37_i6_fu_522_p2");
    sc_trace(mVcdFile, p_not38_i_i_fu_540_p2, "p_not38_i_i_fu_540_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_534_p2, "newsignbit_0_not_i_i_fu_534_p2");
    sc_trace(mVcdFile, brmerge39_i_i_fu_546_p2, "brmerge39_i_i_fu_546_p2");
    sc_trace(mVcdFile, underflow_16_not_i_fu_567_p2, "underflow_16_not_i_fu_567_p2");
    sc_trace(mVcdFile, brmerge_i_i5_i_fu_563_p2, "brmerge_i_i5_i_fu_563_p2");
    sc_trace(mVcdFile, brmerge2_i_fu_572_p2, "brmerge2_i_fu_572_p2");
    sc_trace(mVcdFile, p_Val2_101_mux_i_fu_577_p3, "p_Val2_101_mux_i_fu_577_p3");
    sc_trace(mVcdFile, p_Val2_3_i_fu_584_p3, "p_Val2_3_i_fu_584_p3");
    sc_trace(mVcdFile, tmp_17_fu_612_p1, "tmp_17_fu_612_p1");
    sc_trace(mVcdFile, tmp_18_fu_615_p1, "tmp_18_fu_615_p1");
    sc_trace(mVcdFile, p_Val2_33_fu_619_p2, "p_Val2_33_fu_619_p2");
    sc_trace(mVcdFile, tmp_19_fu_648_p2, "tmp_19_fu_648_p2");
    sc_trace(mVcdFile, isneg_not_fu_662_p2, "isneg_not_fu_662_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_658_p2, "brmerge_i_i_fu_658_p2");
    sc_trace(mVcdFile, underflow_5_fu_653_p2, "underflow_5_fu_653_p2");
    sc_trace(mVcdFile, brmerge_fu_667_p2, "brmerge_fu_667_p2");
    sc_trace(mVcdFile, p_Val2_108_mux_fu_672_p3, "p_Val2_108_mux_fu_672_p3");
    sc_trace(mVcdFile, p_Val2_s_42_fu_679_p3, "p_Val2_s_42_fu_679_p3");
    sc_trace(mVcdFile, grp_fu_320_ce, "grp_fu_320_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("Compult.hdltvin.dat");
    mHdltvoutHandle.open("Compult.hdltvout.dat");
}

Compult::~Compult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_Compult_mpc_pso_fu_113;
    delete Compult_mul_32s_10ns_42_3_U59;
}

void Compult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
            grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Compult_mpc_pso_fu_113_ap_ready.read())) {
            grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        brmerge40_demorgan_i_i_reg_793 = brmerge40_demorgan_i_i_fu_397_p2.read();
        brmerge_i_i2_reg_788 = brmerge_i_i2_fu_392_p2.read();
        qb_assign_8_reg_783 = qb_assign_8_fu_378_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_Compult_mpc_pso_fu_113_ap_done.read()))) {
        du_V_reg_840 = du_V_fu_604_p3.read();
        isneg_3_reg_845 = p_Val2_33_fu_619_p2.read().range(30, 30);
        newsignbit_6_reg_858 = p_Val2_33_fu_619_p2.read().range(29, 29);
        p_Val2_34_reg_852 = p_Val2_34_fu_633_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        dx1_V_reg_740 = dx1_V_fu_309_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        dx2_V_reg_829 = dx2_V_fu_590_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        isneg_reg_715 = p_Val2_22_fu_231_p2.read().range(30, 30);
        newsignbit_reg_728 = p_Val2_22_fu_231_p2.read().range(29, 29);
        p_Val2_20_reg_710 = p_Val2_20_fu_213_p3.read();
        p_Val2_23_reg_722 = p_Val2_23_fu_245_p1.read();
        x1_1_V = p_Val2_20_fu_213_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        newsignbit_4_reg_761 = grp_fu_320_p2.read().range(33, 33);
        p_Result_20_i_reg_777 = grp_fu_320_p2.read().range(41, 34);
        qbit_3_reg_756 = grp_fu_320_p2.read().range(1, 1);
        signbit_reg_750 = grp_fu_320_p2.read().range(41, 41);
        tmp_16_reg_772 = grp_fu_320_p2.read().range(33, 3);
        tmp_58_reg_767 = grp_fu_320_p2.read().range(2, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        overflow_5_reg_811 = overflow_5_fu_528_p2.read();
        p_Val2_29_reg_805 = p_Val2_29_fu_488_p1.read();
        underflow_4_reg_817 = underflow_4_fu_552_p2.read();
        x2_2_V = p_Val2_26_reg_799.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        overflow_reg_705 = overflow_fu_207_p2.read();
        p_Val2_19_reg_700 = p_Val2_19_fu_187_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        p_Val2_26_reg_799 = p_Val2_26_fu_455_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        tmp_21_reg_735 = tmp_21_fu_301_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        u_V = tmp_20_fu_686_p3.read();
    }
}

void Compult::thread_Range1_all_ones_fu_382_p2() {
    Range1_all_ones_fu_382_p2 = (!p_Result_20_i_reg_777.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_20_i_reg_777.read() == ap_const_lv8_FF);
}

void Compult::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Compult::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Compult::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Compult::thread_ap_return() {
    ap_return = esl_sext<30,29>(du_V_reg_840.read());
}

void Compult::thread_ap_sig_bdd_110() {
    ap_sig_bdd_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void Compult::thread_ap_sig_bdd_123() {
    ap_sig_bdd_123 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void Compult::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void Compult::thread_ap_sig_bdd_145() {
    ap_sig_bdd_145 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void Compult::thread_ap_sig_bdd_158() {
    ap_sig_bdd_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void Compult::thread_ap_sig_bdd_225() {
    ap_sig_bdd_225 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void Compult::thread_ap_sig_bdd_28() {
    ap_sig_bdd_28 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void Compult::thread_ap_sig_bdd_56() {
    ap_sig_bdd_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void Compult::thread_ap_sig_bdd_71() {
    ap_sig_bdd_71 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void Compult::thread_ap_sig_bdd_80() {
    ap_sig_bdd_80 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void Compult::thread_ap_sig_bdd_91() {
    ap_sig_bdd_91 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void Compult::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_145.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_158.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_225.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_28.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_56.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_71.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_80.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_91.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_110.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_123.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_132.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void Compult::thread_brmerge2_i_fu_572_p2() {
    brmerge2_i_fu_572_p2 = (overflow_5_reg_811.read() | underflow_16_not_i_fu_567_p2.read());
}

void Compult::thread_brmerge39_i_i_fu_546_p2() {
    brmerge39_i_i_fu_546_p2 = (p_not38_i_i_fu_540_p2.read() | newsignbit_0_not_i_i_fu_534_p2.read());
}

void Compult::thread_brmerge40_demorgan_i_i_fu_397_p2() {
    brmerge40_demorgan_i_i_fu_397_p2 = (newsignbit_4_reg_761.read() & Range1_all_ones_fu_382_p2.read());
}

void Compult::thread_brmerge_fu_667_p2() {
    brmerge_fu_667_p2 = (newsignbit_6_reg_858.read() | isneg_not_fu_662_p2.read());
}

void Compult::thread_brmerge_i6_fu_282_p2() {
    brmerge_i6_fu_282_p2 = (newsignbit_reg_728.read() | isneg_not_i_fu_277_p2.read());
}

void Compult::thread_brmerge_i6_i_fu_516_p2() {
    brmerge_i6_i_fu_516_p2 = (newsignbit_5_fu_492_p3.read() | p_not_i5_i_fu_510_p2.read());
}

void Compult::thread_brmerge_i_i2_fu_392_p2() {
    brmerge_i_i2_fu_392_p2 = (newsignbit_4_reg_761.read() | p_not_i_i_fu_387_p2.read());
}

void Compult::thread_brmerge_i_i5_i_fu_563_p2() {
    brmerge_i_i5_i_fu_563_p2 = (underflow_4_reg_817.read() | overflow_5_reg_811.read());
}

void Compult::thread_brmerge_i_i_fu_658_p2() {
    brmerge_i_i_fu_658_p2 = (isneg_3_reg_845.read() ^ newsignbit_6_reg_858.read());
}

void Compult::thread_brmerge_i_i_i3_fu_428_p2() {
    brmerge_i_i_i3_fu_428_p2 = (underflow_3_fu_423_p2.read() | overflow_4_fu_413_p2.read());
}

void Compult::thread_brmerge_i_i_i_fu_273_p2() {
    brmerge_i_i_i_fu_273_p2 = (isneg_reg_715.read() ^ newsignbit_reg_728.read());
}

void Compult::thread_du_V_fu_604_p3() {
    du_V_fu_604_p3 = esl_concat<27,2>(grp_Compult_mpc_pso_fu_113_ap_return.read(), ap_const_lv2_0);
}

void Compult::thread_dx1_V_fu_309_p3() {
    dx1_V_fu_309_p3 = esl_concat<30,2>(tmp_21_reg_735.read(), ap_const_lv2_0);
}

void Compult::thread_dx2_V_fu_590_p3() {
    dx2_V_fu_590_p3 = (!brmerge2_i_fu_572_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge2_i_fu_572_p2.read()[0].to_bool())? p_Val2_101_mux_i_fu_577_p3.read(): p_Val2_3_i_fu_584_p3.read());
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_ap_start() {
    grp_Compult_mpc_pso_fu_113_ap_start = grp_Compult_mpc_pso_fu_113_ap_start_ap_start_reg.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_dx1_in_V() {
    grp_Compult_mpc_pso_fu_113_dx1_in_V = dx1_V_reg_740.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_dx2_in_V() {
    grp_Compult_mpc_pso_fu_113_dx2_in_V = dx2_V_reg_829.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_ref_in_V() {
    grp_Compult_mpc_pso_fu_113_ref_in_V = ref_in_V.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_u_in_V() {
    grp_Compult_mpc_pso_fu_113_u_in_V = u_V.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_113_y_in_V() {
    grp_Compult_mpc_pso_fu_113_y_in_V = p_Val2_20_reg_710.read();
}

void Compult::thread_grp_fu_320_ce() {
    grp_fu_320_ce = ap_const_logic_1;
}

void Compult::thread_grp_fu_320_p0() {
    grp_fu_320_p0 = dx1_V_fu_309_p3.read();
}

void Compult::thread_grp_fu_320_p1() {
    grp_fu_320_p1 =  (sc_lv<10>) (ap_const_lv42_1F4);
}

void Compult::thread_isneg_2_fu_480_p3() {
    isneg_2_fu_480_p3 = p_Val2_28_fu_474_p2.read().range(32, 32);
}

void Compult::thread_isneg_not_fu_662_p2() {
    isneg_not_fu_662_p2 = (isneg_3_reg_845.read() ^ ap_const_lv1_1);
}

void Compult::thread_isneg_not_i_fu_277_p2() {
    isneg_not_i_fu_277_p2 = (isneg_reg_715.read() ^ ap_const_lv1_1);
}

void Compult::thread_newsignbit_0_not_i_i_fu_534_p2() {
    newsignbit_0_not_i_i_fu_534_p2 = (newsignbit_5_fu_492_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_newsignbit_5_fu_492_p3() {
    newsignbit_5_fu_492_p3 = p_Val2_28_fu_474_p2.read().range(29, 29);
}

void Compult::thread_overflow_4_fu_413_p2() {
    overflow_4_fu_413_p2 = (brmerge_i_i2_reg_788.read() & tmp_34_i_fu_408_p2.read());
}

void Compult::thread_overflow_5_fu_528_p2() {
    overflow_5_fu_528_p2 = (brmerge_i6_i_fu_516_p2.read() & tmp_37_i6_fu_522_p2.read());
}

void Compult::thread_overflow_fu_207_p2() {
    overflow_fu_207_p2 = (tmp_51_fu_193_p3.read() & tmp_15_fu_201_p2.read());
}

void Compult::thread_p_Result_21_i_fu_500_p4() {
    p_Result_21_i_fu_500_p4 = p_Val2_28_fu_474_p2.read().range(32, 30);
}

void Compult::thread_p_Val2_101_mux_i_fu_577_p3() {
    p_Val2_101_mux_i_fu_577_p3 = (!brmerge_i_i5_i_fu_563_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i5_i_fu_563_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_29_reg_805.read());
}

void Compult::thread_p_Val2_108_mux_fu_672_p3() {
    p_Val2_108_mux_fu_672_p3 = (!brmerge_i_i_fu_658_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i_fu_658_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_34_reg_852.read());
}

void Compult::thread_p_Val2_19_fu_187_p2() {
    p_Val2_19_fu_187_p2 = (!p_Val2_s_fu_141_p4.read().is_01() || !tmp_s_fu_183_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(p_Val2_s_fu_141_p4.read()) + sc_biguint<30>(tmp_s_fu_183_p1.read()));
}

void Compult::thread_p_Val2_20_fu_213_p3() {
    p_Val2_20_fu_213_p3 = (!overflow_reg_705.read()[0].is_01())? sc_lv<30>(): ((overflow_reg_705.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_19_reg_700.read());
}

void Compult::thread_p_Val2_22_fu_231_p2() {
    p_Val2_22_fu_231_p2 = (!tmp_i_fu_219_p1.read().is_01() || !tmp_i_41_fu_227_p1.read().is_01())? sc_lv<31>(): (sc_bigint<31>(tmp_i_fu_219_p1.read()) - sc_bigint<31>(tmp_i_41_fu_227_p1.read()));
}

void Compult::thread_p_Val2_23_fu_245_p1() {
    p_Val2_23_fu_245_p1 = p_Val2_22_fu_231_p2.read().range(30-1, 0);
}

void Compult::thread_p_Val2_25_fu_402_p3() {
    p_Val2_25_fu_402_p3 = esl_concat<31,1>(tmp_16_reg_772.read(), qb_assign_8_reg_783.read());
}

void Compult::thread_p_Val2_26_fu_455_p3() {
    p_Val2_26_fu_455_p3 = (!tmp7_fu_434_p2.read()[0].is_01())? sc_lv<32>(): ((tmp7_fu_434_p2.read()[0].to_bool())? p_Val2_97_mux_i_fu_439_p3.read(): p_Val2_i4_fu_447_p3.read());
}

void Compult::thread_p_Val2_28_fu_474_p2() {
    p_Val2_28_fu_474_p2 = (!tmp_35_i_fu_463_p1.read().is_01() || !tmp_36_i5_fu_470_p1.read().is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_35_i_fu_463_p1.read()) - sc_bigint<33>(tmp_36_i5_fu_470_p1.read()));
}

void Compult::thread_p_Val2_29_fu_488_p1() {
    p_Val2_29_fu_488_p1 = p_Val2_28_fu_474_p2.read().range(30-1, 0);
}

void Compult::thread_p_Val2_33_fu_619_p2() {
    p_Val2_33_fu_619_p2 = (!tmp_17_fu_612_p1.read().is_01() || !tmp_18_fu_615_p1.read().is_01())? sc_lv<31>(): (sc_bigint<31>(tmp_17_fu_612_p1.read()) + sc_bigint<31>(tmp_18_fu_615_p1.read()));
}

void Compult::thread_p_Val2_34_fu_633_p1() {
    p_Val2_34_fu_633_p1 = p_Val2_33_fu_619_p2.read().range(30-1, 0);
}

void Compult::thread_p_Val2_3_i_fu_584_p3() {
    p_Val2_3_i_fu_584_p3 = (!underflow_4_reg_817.read()[0].is_01())? sc_lv<30>(): ((underflow_4_reg_817.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_29_reg_805.read());
}

void Compult::thread_p_Val2_94_mux_i_fu_287_p3() {
    p_Val2_94_mux_i_fu_287_p3 = (!brmerge_i_i_i_fu_273_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i_i_fu_273_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_23_reg_722.read());
}

void Compult::thread_p_Val2_97_mux_i_fu_439_p3() {
    p_Val2_97_mux_i_fu_439_p3 = (!brmerge_i_i_i3_fu_428_p2.read()[0].is_01())? sc_lv<32>(): ((brmerge_i_i_i3_fu_428_p2.read()[0].to_bool())? ap_const_lv32_7FFFFFFF: p_Val2_25_fu_402_p3.read());
}

void Compult::thread_p_Val2_i4_fu_447_p3() {
    p_Val2_i4_fu_447_p3 = (!underflow_3_fu_423_p2.read()[0].is_01())? sc_lv<32>(): ((underflow_3_fu_423_p2.read()[0].to_bool())? ap_const_lv32_80000000: p_Val2_25_fu_402_p3.read());
}

void Compult::thread_p_Val2_i_fu_294_p3() {
    p_Val2_i_fu_294_p3 = (!underflow_fu_268_p2.read()[0].is_01())? sc_lv<30>(): ((underflow_fu_268_p2.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_23_reg_722.read());
}

void Compult::thread_p_Val2_s_42_fu_679_p3() {
    p_Val2_s_42_fu_679_p3 = (!underflow_5_fu_653_p2.read()[0].is_01())? sc_lv<30>(): ((underflow_5_fu_653_p2.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_34_reg_852.read());
}

void Compult::thread_p_Val2_s_fu_141_p4() {
    p_Val2_s_fu_141_p4 = y_in_V.read().range(31, 2);
}

void Compult::thread_p_not38_i_i_fu_540_p2() {
    p_not38_i_i_fu_540_p2 = (!p_Result_21_i_fu_500_p4.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_21_i_fu_500_p4.read() != ap_const_lv3_7);
}

void Compult::thread_p_not_i5_i_fu_510_p2() {
    p_not_i5_i_fu_510_p2 = (!p_Result_21_i_fu_500_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_21_i_fu_500_p4.read() != ap_const_lv3_0);
}

void Compult::thread_p_not_i_i_fu_387_p2() {
    p_not_i_i_fu_387_p2 = (!p_Result_20_i_reg_777.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_20_i_reg_777.read() != ap_const_lv8_0);
}

void Compult::thread_qb_assign_6_fu_177_p2() {
    qb_assign_6_fu_177_p2 = (r_i_i_fu_171_p2.read() & qbit_fu_151_p3.read());
}

void Compult::thread_qb_assign_8_fu_378_p2() {
    qb_assign_8_fu_378_p2 = (tmp_58_reg_767.read() & qbit_3_reg_756.read());
}

void Compult::thread_qbit_fu_151_p3() {
    qbit_fu_151_p3 = y_in_V.read().range(1, 1);
}

void Compult::thread_r_fu_159_p1() {
    r_fu_159_p1 = y_in_V.read().range(1-1, 0);
}

void Compult::thread_r_i_i_fu_171_p2() {
    r_i_i_fu_171_p2 = (tmp_50_fu_163_p3.read() | r_fu_159_p1.read());
}

void Compult::thread_tmp7_fu_434_p2() {
    tmp7_fu_434_p2 = (brmerge40_demorgan_i_i_reg_793.read() | tmp_34_i_fu_408_p2.read());
}

void Compult::thread_tmp_15_fu_201_p2() {
    tmp_15_fu_201_p2 = (tmp_47_fu_133_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_17_fu_612_p1() {
    tmp_17_fu_612_p1 = esl_sext<31,30>(u_V.read());
}

void Compult::thread_tmp_18_fu_615_p1() {
    tmp_18_fu_615_p1 = esl_sext<31,29>(du_V_fu_604_p3.read());
}

void Compult::thread_tmp_19_fu_648_p2() {
    tmp_19_fu_648_p2 = (newsignbit_6_reg_858.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_20_fu_686_p3() {
    tmp_20_fu_686_p3 = (!brmerge_fu_667_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_fu_667_p2.read()[0].to_bool())? p_Val2_108_mux_fu_672_p3.read(): p_Val2_s_42_fu_679_p3.read());
}

void Compult::thread_tmp_21_fu_301_p3() {
    tmp_21_fu_301_p3 = (!brmerge_i6_fu_282_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i6_fu_282_p2.read()[0].to_bool())? p_Val2_94_mux_i_fu_287_p3.read(): p_Val2_i_fu_294_p3.read());
}

void Compult::thread_tmp_34_i_fu_408_p2() {
    tmp_34_i_fu_408_p2 = (signbit_reg_750.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_35_i_fu_463_p1() {
    tmp_35_i_fu_463_p1 = esl_sext<33,32>(p_Val2_26_reg_799.read());
}

void Compult::thread_tmp_36_i5_fu_470_p1() {
    tmp_36_i5_fu_470_p1 = esl_sext<33,32>(x2_2_V.read());
}

void Compult::thread_tmp_36_i_fu_263_p2() {
    tmp_36_i_fu_263_p2 = (newsignbit_reg_728.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_37_i6_fu_522_p2() {
    tmp_37_i6_fu_522_p2 = (isneg_2_fu_480_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_47_fu_133_p3() {
    tmp_47_fu_133_p3 = y_in_V.read().range(31, 31);
}

void Compult::thread_tmp_50_fu_163_p3() {
    tmp_50_fu_163_p3 = y_in_V.read().range(2, 2);
}

void Compult::thread_tmp_51_fu_193_p3() {
    tmp_51_fu_193_p3 = p_Val2_19_fu_187_p2.read().range(29, 29);
}

void Compult::thread_tmp_fu_418_p2() {
    tmp_fu_418_p2 = (brmerge40_demorgan_i_i_reg_793.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_i_41_fu_227_p1() {
    tmp_i_41_fu_227_p1 = esl_sext<31,30>(x1_1_V.read());
}

void Compult::thread_tmp_i_fu_219_p1() {
    tmp_i_fu_219_p1 = esl_sext<31,30>(p_Val2_20_fu_213_p3.read());
}

void Compult::thread_tmp_s_fu_183_p1() {
    tmp_s_fu_183_p1 = esl_zext<30,1>(qb_assign_6_fu_177_p2.read());
}

void Compult::thread_underflow_16_not_i_fu_567_p2() {
    underflow_16_not_i_fu_567_p2 = (underflow_4_reg_817.read() ^ ap_const_lv1_1);
}

void Compult::thread_underflow_3_fu_423_p2() {
    underflow_3_fu_423_p2 = (signbit_reg_750.read() & tmp_fu_418_p2.read());
}

void Compult::thread_underflow_4_fu_552_p2() {
    underflow_4_fu_552_p2 = (brmerge39_i_i_fu_546_p2.read() & isneg_2_fu_480_p3.read());
}

void Compult::thread_underflow_5_fu_653_p2() {
    underflow_5_fu_653_p2 = (isneg_3_reg_845.read() & tmp_19_fu_648_p2.read());
}

void Compult::thread_underflow_fu_268_p2() {
    underflow_fu_268_p2 = (isneg_reg_715.read() & tmp_36_i_fu_263_p2.read());
}

void Compult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Compult_mpc_pso_fu_113_ap_done.read())) {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXX";
            break;
    }
}

void Compult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y_in_V\" :  \"" << y_in_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ref_in_V\" :  \"" << ref_in_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

