// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __Compult_pso_ww_H__
#define __Compult_pso_ww_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct Compult_pso_ww_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 18;
  static const unsigned AddressRange = 20;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(Compult_pso_ww_ram) {
        ram[0] = "0b110001010001111011";
        ram[1] = "0b101111010111000011";
        ram[2] = "0b101101011100001010";
        ram[3] = "0b101011100001010010";
        ram[4] = "0b101001100110011010";
        ram[5] = "0b100111101011100001";
        ram[6] = "0b100101110000101001";
        ram[7] = "0b100011110101110001";
        ram[8] = "0b100001111010111000";
        ram[9] = "0b100000000000000000";
        ram[10] = "0b011110000101001000";
        ram[11] = "0b011100001010001111";
        ram[12] = "0b011010001111010111";
        ram[13] = "0b011000010100011111";
        ram[14] = "0b010110011001100110";
        ram[15] = "0b010100011110101110";
        ram[16] = "0b010010100011110110";
        ram[17] = "0b010000101000111101";
        ram[18] = "0b001110101110000101";
        ram[19] = "0b001100110011001101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(Compult_pso_ww) {


static const unsigned DataWidth = 18;
static const unsigned AddressRange = 20;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


Compult_pso_ww_ram* meminst;


SC_CTOR(Compult_pso_ww) {
meminst = new Compult_pso_ww_ram("Compult_pso_ww_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~Compult_pso_ww() {
    delete meminst;
}


};//endmodule
#endif
