// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _Compult_randac_HH_
#define _Compult_randac_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Compult_mul_31s_7ns_38_3.h"

namespace ap_rtl {

struct Compult_randac : public sc_module {
    // Port declarations 7
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<20> > ap_return;


    // Module declarations
    Compult_randac(sc_module_name name);
    SC_HAS_PROCESS(Compult_randac);

    ~Compult_randac();

    sc_trace_file* mVcdFile;

    Compult_mul_31s_7ns_38_3<1,3,31,7,38>* Compult_mul_31s_7ns_38_3_U0;
    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_26;
    sc_signal< sc_lv<31> > seed_V;
    sc_signal< sc_lv<1> > tmp_5_reg_502;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_46;
    sc_signal< sc_lv<5> > tmp_6_fu_103_p1;
    sc_signal< sc_lv<5> > tmp_6_reg_507;
    sc_signal< sc_lv<32> > tmp_10_reg_512;
    sc_signal< sc_lv<32> > tmp_4_reg_517;
    sc_signal< sc_lv<1> > tmp_12_reg_523;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_61;
    sc_signal< sc_lv<20> > tmp_13_fu_158_p1;
    sc_signal< sc_lv<20> > tmp_13_reg_528;
    sc_signal< sc_lv<20> > tmp_16_fu_162_p1;
    sc_signal< sc_lv<20> > tmp_16_reg_533;
    sc_signal< sc_lv<1> > isneg_reg_538;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_74;
    sc_signal< sc_lv<25> > tmp_19_fu_207_p1;
    sc_signal< sc_lv<25> > tmp_19_reg_544;
    sc_signal< sc_lv<1> > newsignbit_reg_549;
    sc_signal< sc_lv<7> > p_Result_s_reg_555;
    sc_signal< sc_lv<1> > overflow_fu_244_p2;
    sc_signal< sc_lv<1> > overflow_reg_561;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_89;
    sc_signal< sc_lv<1> > underflow_fu_266_p2;
    sc_signal< sc_lv<1> > underflow_reg_567;
    sc_signal< sc_lv<25> > ret_V_reg_574;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_100;
    sc_signal< sc_lv<1> > isneg_1_reg_581;
    sc_signal< sc_lv<1> > tmp_3_fu_337_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_588;
    sc_signal< sc_lv<17> > tmp_14_reg_593;
    sc_signal< sc_lv<1> > newsignbit_1_fu_353_p3;
    sc_signal< sc_lv<1> > newsignbit_1_reg_598;
    sc_signal< sc_lv<1> > p_not_i_fu_371_p2;
    sc_signal< sc_lv<1> > p_not_i_reg_603;
    sc_signal< sc_lv<1> > newsignbit_0_not_i_fu_377_p2;
    sc_signal< sc_lv<1> > newsignbit_0_not_i_reg_608;
    sc_signal< sc_lv<1> > p_not38_i_fu_383_p2;
    sc_signal< sc_lv<1> > p_not38_i_reg_613;
    sc_signal< sc_lv<31> > p_Val2_4_cast_fu_414_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_122;
    sc_signal< sc_lv<31> > grp_fu_89_p0;
    sc_signal< sc_lv<7> > grp_fu_89_p1;
    sc_signal< sc_lv<38> > grp_fu_89_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_127_p2;
    sc_signal< sc_lv<32> > tmp_11_fu_132_p2;
    sc_signal< sc_lv<32> > tmp_7_fu_137_p3;
    sc_signal< sc_lv<32> > tmp_9_fu_144_p3;
    sc_signal< sc_lv<20> > tmp_17_fu_173_p2;
    sc_signal< sc_lv<32> > p_and_t_fu_178_p3;
    sc_signal< sc_lv<32> > p_neg_t_fu_186_p2;
    sc_signal< sc_lv<32> > p_and_f_fu_166_p3;
    sc_signal< sc_lv<32> > p_Val2_1_fu_192_p3;
    sc_signal< sc_lv<1> > p_not_i_i1_fu_229_p2;
    sc_signal< sc_lv<1> > brmerge_i_i1_fu_234_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_239_p2;
    sc_signal< sc_lv<1> > p_not38_i_i1_fu_255_p2;
    sc_signal< sc_lv<1> > newsignbit_0_not_i_i1_fu_250_p2;
    sc_signal< sc_lv<1> > brmerge39_i_i1_fu_260_p2;
    sc_signal< sc_lv<1> > underflow_not_fu_282_p2;
    sc_signal< sc_lv<1> > brmerge_i_i_i1_fu_278_p2;
    sc_signal< sc_lv<41> > p_Val2_2_fu_271_p3;
    sc_signal< sc_lv<1> > brmerge_fu_287_p2;
    sc_signal< sc_lv<41> > p_Val2_2_mux_fu_292_p3;
    sc_signal< sc_lv<41> > p_Val2_2_35_fu_300_p3;
    sc_signal< sc_lv<41> > p_Val2_3_fu_307_p3;
    sc_signal< sc_lv<16> > tmp_22_fu_333_p1;
    sc_signal< sc_lv<4> > tmp_fu_361_p4;
    sc_signal< sc_lv<25> > ret_V_1_fu_389_p2;
    sc_signal< sc_lv<25> > p_3_fu_394_p3;
    sc_signal< sc_lv<25> > tmp_s_fu_400_p3;
    sc_signal< sc_lv<30> > p_Val2_4_fu_406_p3;
    sc_signal< sc_lv<1> > brmerge_i_fu_431_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_435_p2;
    sc_signal< sc_lv<1> > brmerge39_i_fu_446_p2;
    sc_signal< sc_lv<1> > underflow_1_fu_450_p2;
    sc_signal< sc_lv<1> > overflow_1_fu_440_p2;
    sc_signal< sc_lv<1> > underflow_2_not_fu_461_p2;
    sc_signal< sc_lv<1> > brmerge_i_i2_fu_455_p2;
    sc_signal< sc_lv<20> > p_Val2_5_fu_424_p3;
    sc_signal< sc_lv<1> > brmerge4_fu_467_p2;
    sc_signal< sc_lv<20> > result_V_fu_473_p3;
    sc_signal< sc_lv<20> > p_Val2_7_fu_481_p3;
    sc_signal< sc_logic > grp_fu_89_ce;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_st1_fsm_0;
    static const sc_lv<8> ap_ST_st2_fsm_1;
    static const sc_lv<8> ap_ST_st3_fsm_2;
    static const sc_lv<8> ap_ST_st4_fsm_3;
    static const sc_lv<8> ap_ST_st5_fsm_4;
    static const sc_lv<8> ap_ST_st6_fsm_5;
    static const sc_lv<8> ap_ST_st7_fsm_6;
    static const sc_lv<8> ap_ST_st8_fsm_7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<38> ap_const_lv38_2D;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<20> ap_const_lv20_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<7> ap_const_lv7_7F;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<41> ap_const_lv41_FFFFFFFFFF;
    static const sc_lv<41> ap_const_lv41_10000000000;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<25> ap_const_lv25_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<20> ap_const_lv20_7FFFF;
    static const sc_lv<20> ap_const_lv20_80000;
    static const sc_lv<1> ap_const_lv1_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_bdd_100();
    void thread_ap_sig_bdd_122();
    void thread_ap_sig_bdd_26();
    void thread_ap_sig_bdd_46();
    void thread_ap_sig_bdd_61();
    void thread_ap_sig_bdd_74();
    void thread_ap_sig_bdd_89();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_brmerge39_i_fu_446_p2();
    void thread_brmerge39_i_i1_fu_260_p2();
    void thread_brmerge4_fu_467_p2();
    void thread_brmerge_fu_287_p2();
    void thread_brmerge_i_fu_431_p2();
    void thread_brmerge_i_i1_fu_234_p2();
    void thread_brmerge_i_i2_fu_455_p2();
    void thread_brmerge_i_i_i1_fu_278_p2();
    void thread_grp_fu_89_ce();
    void thread_grp_fu_89_p0();
    void thread_grp_fu_89_p1();
    void thread_newsignbit_0_not_i_fu_377_p2();
    void thread_newsignbit_0_not_i_i1_fu_250_p2();
    void thread_newsignbit_1_fu_353_p3();
    void thread_overflow_1_fu_440_p2();
    void thread_overflow_fu_244_p2();
    void thread_p_3_fu_394_p3();
    void thread_p_Val2_1_fu_192_p3();
    void thread_p_Val2_2_35_fu_300_p3();
    void thread_p_Val2_2_fu_271_p3();
    void thread_p_Val2_2_mux_fu_292_p3();
    void thread_p_Val2_3_fu_307_p3();
    void thread_p_Val2_4_cast_fu_414_p1();
    void thread_p_Val2_4_fu_406_p3();
    void thread_p_Val2_5_fu_424_p3();
    void thread_p_Val2_7_fu_481_p3();
    void thread_p_and_f_fu_166_p3();
    void thread_p_and_t_fu_178_p3();
    void thread_p_neg_t_fu_186_p2();
    void thread_p_not38_i_fu_383_p2();
    void thread_p_not38_i_i1_fu_255_p2();
    void thread_p_not_i_fu_371_p2();
    void thread_p_not_i_i1_fu_229_p2();
    void thread_result_V_fu_473_p3();
    void thread_ret_V_1_fu_389_p2();
    void thread_tmp_11_fu_132_p2();
    void thread_tmp_13_fu_158_p1();
    void thread_tmp_16_fu_162_p1();
    void thread_tmp_17_fu_173_p2();
    void thread_tmp_19_fu_207_p1();
    void thread_tmp_1_fu_239_p2();
    void thread_tmp_22_fu_333_p1();
    void thread_tmp_2_fu_127_p2();
    void thread_tmp_3_fu_337_p2();
    void thread_tmp_6_fu_103_p1();
    void thread_tmp_7_fu_137_p3();
    void thread_tmp_8_fu_435_p2();
    void thread_tmp_9_fu_144_p3();
    void thread_tmp_fu_361_p4();
    void thread_tmp_s_fu_400_p3();
    void thread_underflow_1_fu_450_p2();
    void thread_underflow_2_not_fu_461_p2();
    void thread_underflow_fu_266_p2();
    void thread_underflow_not_fu_282_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
