// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __Compult_mpc_pso_Sx_1_H__
#define __Compult_mpc_pso_Sx_1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct Compult_mpc_pso_Sx_1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 22;
  static const unsigned AddressRange = 20;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(Compult_mpc_pso_Sx_1_ram) {
        ram[0] = "0b0000000100000001001001";
        ram[1] = "0b0000001011111001101010";
        ram[2] = "0b0000010111100000001100";
        ram[3] = "0b0000100110101011101011";
        ram[4] = "0b0000111001010011011101";
        ram[5] = "0b0001001111001111001001";
        ram[6] = "0b0001101000010110101110";
        ram[7] = "0b0010000100100010011101";
        ram[8] = "0b0010100011101010111001";
        ram[9] = "0b0011000101101000111000";
        ram[10] = "0b0011101010010101100001";
        ram[11] = "0b0100010001101010001100";
        ram[12] = "0b0100111011100000100001";
        ram[13] = "0b0101100111110010010111";
        ram[14] = "0b0110010110011001110110";
        ram[15] = "0b0111000111010001010001";
        ram[16] = "0b0111111010010011001010";
        ram[17] = "0b1000101111011010010011";
        ram[18] = "0b1001100110100001100110";
        ram[19] = "0b1010011111100100001110";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(Compult_mpc_pso_Sx_1) {


static const unsigned DataWidth = 22;
static const unsigned AddressRange = 20;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


Compult_mpc_pso_Sx_1_ram* meminst;


SC_CTOR(Compult_mpc_pso_Sx_1) {
meminst = new Compult_mpc_pso_Sx_1_ram("Compult_mpc_pso_Sx_1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~Compult_mpc_pso_Sx_1() {
    delete meminst;
}


};//endmodule
#endif
