// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "Compult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Compult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Compult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> Compult::ap_ST_st1_fsm_0 = "1";
const sc_lv<24> Compult::ap_ST_st2_fsm_1 = "10";
const sc_lv<24> Compult::ap_ST_st3_fsm_2 = "100";
const sc_lv<24> Compult::ap_ST_st4_fsm_3 = "1000";
const sc_lv<24> Compult::ap_ST_st5_fsm_4 = "10000";
const sc_lv<24> Compult::ap_ST_st6_fsm_5 = "100000";
const sc_lv<24> Compult::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<24> Compult::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<24> Compult::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<24> Compult::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<24> Compult::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<24> Compult::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<24> Compult::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<24> Compult::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<24> Compult::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<24> Compult::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<24> Compult::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<24> Compult::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<24> Compult::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<24> Compult::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<24> Compult::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<24> Compult::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<24> Compult::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<24> Compult::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<32> Compult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Compult::ap_const_lv1_1 = "1";
const sc_lv<32> Compult::ap_const_lv32_1 = "1";
const sc_lv<32> Compult::ap_const_lv32_2 = "10";
const sc_lv<32> Compult::ap_const_lv32_3 = "11";
const sc_lv<32> Compult::ap_const_lv32_4 = "100";
const sc_lv<32> Compult::ap_const_lv32_6 = "110";
const sc_lv<32> Compult::ap_const_lv32_7 = "111";
const sc_lv<32> Compult::ap_const_lv32_8 = "1000";
const sc_lv<32> Compult::ap_const_lv32_9 = "1001";
const sc_lv<32> Compult::ap_const_lv32_A = "1010";
const sc_lv<32> Compult::ap_const_lv32_B = "1011";
const sc_lv<32> Compult::ap_const_lv32_C = "1100";
const sc_lv<32> Compult::ap_const_lv32_D = "1101";
const sc_lv<32> Compult::ap_const_lv32_12 = "10010";
const sc_lv<32> Compult::ap_const_lv32_13 = "10011";
const sc_lv<32> Compult::ap_const_lv32_14 = "10100";
const sc_lv<32> Compult::ap_const_lv32_15 = "10101";
const sc_lv<32> Compult::ap_const_lv32_16 = "10110";
const sc_lv<36> Compult::ap_const_lv36_73333 = "1110011001100110011";
const sc_lv<32> Compult::ap_const_lv32_22 = "100010";
const sc_lv<18> Compult::ap_const_lv18_0 = "000000000000000000";
const sc_lv<32> Compult::ap_const_lv32_F = "1111";
const sc_lv<16> Compult::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<12> Compult::ap_const_lv12_0 = "000000000000";
const sc_lv<2> Compult::ap_const_lv2_0 = "00";
const sc_lv<41> Compult::ap_const_lv41_1F4 = "111110100";
const sc_lv<32> Compult::ap_const_lv32_28 = "101000";
const sc_lv<32> Compult::ap_const_lv32_21 = "100001";
const sc_lv<7> Compult::ap_const_lv7_7F = "1111111";
const sc_lv<7> Compult::ap_const_lv7_0 = "0000000";
const sc_lv<32> Compult::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> Compult::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<32> Compult::ap_const_lv32_20 = "100000";
const sc_lv<32> Compult::ap_const_lv32_1D = "11101";
const sc_lv<32> Compult::ap_const_lv32_1E = "11110";
const sc_lv<3> Compult::ap_const_lv3_0 = "000";
const sc_lv<3> Compult::ap_const_lv3_7 = "111";
const sc_lv<30> Compult::ap_const_lv30_1FFFFFFF = "11111111111111111111111111111";
const sc_lv<30> Compult::ap_const_lv30_20000000 = "100000000000000000000000000000";
const sc_lv<55> Compult::ap_const_lv55_1D4C000 = "1110101001100000000000000";
const sc_lv<32> Compult::ap_const_lv32_36 = "110110";
const sc_lv<32> Compult::ap_const_lv32_25 = "100101";
const sc_lv<32> Compult::ap_const_lv32_34 = "110100";
const sc_lv<32> Compult::ap_const_lv32_24 = "100100";
const sc_lv<32> Compult::ap_const_lv32_35 = "110101";
const sc_lv<36> Compult::ap_const_lv36_0 = "000000000000000000000000000000000000";
const sc_lv<2> Compult::ap_const_lv2_3 = "11";
const sc_lv<16> Compult::ap_const_lv16_7FFF = "111111111111111";
const sc_lv<16> Compult::ap_const_lv16_8000 = "1000000000000000";
const sc_lv<13> Compult::ap_const_lv13_0 = "0000000000000";
const sc_lv<13> Compult::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<27> Compult::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<32> Compult::ap_const_lv32_17 = "10111";

Compult::Compult(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_Compult_mpc_pso_fu_161 = new Compult_mpc_pso("grp_Compult_mpc_pso_fu_161");
    grp_Compult_mpc_pso_fu_161->ap_clk(ap_clk);
    grp_Compult_mpc_pso_fu_161->ap_rst(ap_rst);
    grp_Compult_mpc_pso_fu_161->ap_start(grp_Compult_mpc_pso_fu_161_ap_start);
    grp_Compult_mpc_pso_fu_161->ap_done(grp_Compult_mpc_pso_fu_161_ap_done);
    grp_Compult_mpc_pso_fu_161->ap_idle(grp_Compult_mpc_pso_fu_161_ap_idle);
    grp_Compult_mpc_pso_fu_161->ap_ready(grp_Compult_mpc_pso_fu_161_ap_ready);
    grp_Compult_mpc_pso_fu_161->dx1_in_V(grp_Compult_mpc_pso_fu_161_dx1_in_V);
    grp_Compult_mpc_pso_fu_161->dx2_in_V(grp_Compult_mpc_pso_fu_161_dx2_in_V);
    grp_Compult_mpc_pso_fu_161->y_in_V(grp_Compult_mpc_pso_fu_161_y_in_V);
    grp_Compult_mpc_pso_fu_161->u_in_V(grp_Compult_mpc_pso_fu_161_u_in_V);
    grp_Compult_mpc_pso_fu_161->ref_in_V(grp_Compult_mpc_pso_fu_161_ref_in_V);
    grp_Compult_mpc_pso_fu_161->ap_return(grp_Compult_mpc_pso_fu_161_ap_return);
    Compult_mul_31s_10ns_41_3_U59 = new Compult_mul_31s_10ns_41_3<1,3,31,10,41>("Compult_mul_31s_10ns_41_3_U59");
    Compult_mul_31s_10ns_41_3_U59->clk(ap_clk);
    Compult_mul_31s_10ns_41_3_U59->reset(ap_rst);
    Compult_mul_31s_10ns_41_3_U59->din0(grp_fu_316_p0);
    Compult_mul_31s_10ns_41_3_U59->din1(grp_fu_316_p1);
    Compult_mul_31s_10ns_41_3_U59->ce(grp_fu_316_ce);
    Compult_mul_31s_10ns_41_3_U59->dout(grp_fu_316_p2);
    Compult_mul_30s_26ns_55_6_U60 = new Compult_mul_30s_26ns_55_6<1,6,30,26,55>("Compult_mul_30s_26ns_55_6_U60");
    Compult_mul_30s_26ns_55_6_U60->clk(ap_clk);
    Compult_mul_30s_26ns_55_6_U60->reset(ap_rst);
    Compult_mul_30s_26ns_55_6_U60->din0(grp_fu_802_p0);
    Compult_mul_30s_26ns_55_6_U60->din1(grp_fu_802_p1);
    Compult_mul_30s_26ns_55_6_U60->ce(grp_fu_802_ce);
    Compult_mul_30s_26ns_55_6_U60->dout(grp_fu_802_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Range1_all_ones_3_fu_426_p2);
    sensitive << ( tmp_38_reg_1238 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_Range1_all_ones_fu_914_p2);
    sensitive << ( tmp_8_reg_1408 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );

    SC_METHOD(thread_Range1_all_zeros_fu_919_p2);
    sensitive << ( tmp_8_reg_1408 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( brmerge7_fu_1126_p2 );
    sensitive << ( p_Val2_120_mux_fu_1132_p3 );
    sensitive << ( p_Val2_5_fu_1140_p3 );

    SC_METHOD(thread_ap_sig_bdd_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_115);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_134);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_157);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_168);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_183);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_198);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_215);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_224);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_233);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_256);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_265);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_282);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_295);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_774);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_84);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_168 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_183 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_198 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_215 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_224 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_233 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_40 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_256 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_265 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_bdd_282 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_295 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_bdd_774 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_75 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_84 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_93 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_115 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_134 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_157 );

    SC_METHOD(thread_brmerge2_i_fu_666_p2);
    sensitive << ( overflow_2_reg_1302 );
    sensitive << ( underflow_16_not_i_fu_661_p2 );

    SC_METHOD(thread_brmerge39_i_fu_1087_p2);
    sensitive << ( p_not38_i_fu_1081_p2 );
    sensitive << ( newsignbit_0_not_i_fu_1075_p2 );

    SC_METHOD(thread_brmerge39_i_i_fu_629_p2);
    sensitive << ( p_not38_i_i_fu_623_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_617_p2 );

    SC_METHOD(thread_brmerge40_demorgan_i_fu_977_p2);
    sensitive << ( newsignbit_4_reg_1425 );
    sensitive << ( deleted_ones_reg_1436 );

    SC_METHOD(thread_brmerge40_demorgan_i_i_fu_441_p2);
    sensitive << ( newsignbit_reg_1222 );
    sensitive << ( Range1_all_ones_3_fu_426_p2 );

    SC_METHOD(thread_brmerge7_fu_1126_p2);
    sensitive << ( overflow_4_fu_1105_p2 );
    sensitive << ( underflow_18_not_fu_1120_p2 );

    SC_METHOD(thread_brmerge_fu_766_p2);
    sensitive << ( newsignbit_3_reg_1354 );
    sensitive << ( isneg_not_fu_761_p2 );

    SC_METHOD(thread_brmerge_i6_i_fu_599_p2);
    sensitive << ( newsignbit_2_fu_575_p3 );
    sensitive << ( p_not_i5_i_fu_593_p2 );

    SC_METHOD(thread_brmerge_i7_fu_961_p2);
    sensitive << ( newsignbit_4_reg_1425 );
    sensitive << ( p_not_i_fu_956_p2 );

    SC_METHOD(thread_brmerge_i8_fu_1069_p2);
    sensitive << ( newsignbit_5_fu_1045_p3 );
    sensitive << ( p_not_i6_fu_1063_p2 );

    SC_METHOD(thread_brmerge_i_i2_fu_436_p2);
    sensitive << ( newsignbit_reg_1222 );
    sensitive << ( p_not_i_i_fu_431_p2 );

    SC_METHOD(thread_brmerge_i_i5_i_fu_657_p2);
    sensitive << ( overflow_2_reg_1302 );
    sensitive << ( underflow_2_reg_1308 );

    SC_METHOD(thread_brmerge_i_i6_fu_997_p2);
    sensitive << ( underflow_4_fu_992_p2 );
    sensitive << ( overflow_3_fu_971_p2 );

    SC_METHOD(thread_brmerge_i_i7_fu_1114_p2);
    sensitive << ( underflow_5_fu_1110_p2 );
    sensitive << ( overflow_4_fu_1105_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_757_p2);
    sensitive << ( isneg_2_reg_1341 );
    sensitive << ( newsignbit_3_reg_1354 );

    SC_METHOD(thread_brmerge_i_i_i3_fu_487_p2);
    sensitive << ( underflow_fu_482_p2 );
    sensitive << ( overflow_fu_472_p2 );

    SC_METHOD(thread_carry_fu_909_p2);
    sensitive << ( tmp_48_reg_1393 );
    sensitive << ( tmp_2_fu_903_p2 );

    SC_METHOD(thread_deleted_ones_fu_942_p3);
    sensitive << ( carry_fu_909_p2 );
    sensitive << ( Range1_all_ones_fu_914_p2 );
    sensitive << ( p_41_i_fu_937_p2 );

    SC_METHOD(thread_deleted_zeros_fu_924_p3);
    sensitive << ( carry_fu_909_p2 );
    sensitive << ( Range1_all_ones_fu_914_p2 );
    sensitive << ( Range1_all_zeros_fu_919_p2 );

    SC_METHOD(thread_dx1_V_fu_653_p1);
    sensitive << ( tmp_16_reg_1201 );

    SC_METHOD(thread_dx2_V_fu_684_p3);
    sensitive << ( brmerge2_i_fu_666_p2 );
    sensitive << ( p_Val2_101_mux_i_fu_671_p3 );
    sensitive << ( p_Val2_3_i_fu_678_p3 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_ap_start);
    sensitive << ( grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_dx1_in_V);
    sensitive << ( dx1_V_reg_1320 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_dx2_in_V);
    sensitive << ( dx2_V_reg_1325 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_ref_in_V);
    sensitive << ( this_assign_s_reg_1336 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_u_in_V);
    sensitive << ( u_V );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_grp_Compult_mpc_pso_fu_161_y_in_V);
    sensitive << ( p_Val2_11_reg_1191 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_grp_fu_316_ce);

    SC_METHOD(thread_grp_fu_316_p0);
    sensitive << ( tmp_16_fu_305_p3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_grp_fu_316_p1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_grp_fu_802_ce);

    SC_METHOD(thread_grp_fu_802_p0);
    sensitive << ( tmp_7_reg_1361 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_grp_fu_802_p1);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_isneg_fu_563_p3);
    sensitive << ( p_Val2_17_fu_557_p2 );

    SC_METHOD(thread_isneg_not_fu_761_p2);
    sensitive << ( isneg_2_reg_1341 );

    SC_METHOD(thread_newsignbit_0_not_i_fu_1075_p2);
    sensitive << ( newsignbit_5_fu_1045_p3 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_617_p2);
    sensitive << ( newsignbit_2_fu_575_p3 );

    SC_METHOD(thread_newsignbit_2_fu_575_p3);
    sensitive << ( p_Val2_17_fu_557_p2 );

    SC_METHOD(thread_newsignbit_4_fu_895_p3);
    sensitive << ( p_Val2_26_fu_890_p2 );

    SC_METHOD(thread_newsignbit_5_fu_1045_p3);
    sensitive << ( u_out_V_fu_1026_p3 );

    SC_METHOD(thread_overflow_2_fu_611_p2);
    sensitive << ( brmerge_i6_i_fu_599_p2 );
    sensitive << ( tmp_37_i6_fu_605_p2 );

    SC_METHOD(thread_overflow_3_fu_971_p2);
    sensitive << ( brmerge_i7_fu_961_p2 );
    sensitive << ( tmp_11_fu_966_p2 );

    SC_METHOD(thread_overflow_4_fu_1105_p2);
    sensitive << ( brmerge_i8_reg_1473 );
    sensitive << ( tmp_12_fu_1100_p2 );

    SC_METHOD(thread_overflow_fu_472_p2);
    sensitive << ( brmerge_i_i2_reg_1274 );
    sensitive << ( tmp_34_i_fu_467_p2 );

    SC_METHOD(thread_p_38_i_fu_950_p2);
    sensitive << ( carry_fu_909_p2 );
    sensitive << ( Range1_all_ones_fu_914_p2 );

    SC_METHOD(thread_p_41_i_fu_937_p2);
    sensitive << ( signbit_1_reg_1371 );
    sensitive << ( tmp_10_fu_932_p2 );

    SC_METHOD(thread_p_Result_21_i_fu_583_p4);
    sensitive << ( p_Val2_17_fu_557_p2 );

    SC_METHOD(thread_p_Result_s_fu_1053_p4);
    sensitive << ( u_out_V_fu_1026_p3 );

    SC_METHOD(thread_p_Val2_101_mux_i_fu_671_p3);
    sensitive << ( p_Val2_18_reg_1296 );
    sensitive << ( brmerge_i_i5_i_fu_657_p2 );

    SC_METHOD(thread_p_Val2_10_fu_525_p2);
    sensitive << ( p_Val2_9_reg_1244 );
    sensitive << ( tmp_3_fu_522_p1 );

    SC_METHOD(thread_p_Val2_115_mux_fu_771_p3);
    sensitive << ( p_Val2_23_reg_1348 );
    sensitive << ( brmerge_i_i_fu_757_p2 );

    SC_METHOD(thread_p_Val2_118_mux_fu_1014_p3);
    sensitive << ( p_Val2_26_reg_1419 );
    sensitive << ( brmerge_i_i6_reg_1452 );

    SC_METHOD(thread_p_Val2_11_fu_274_p3);
    sensitive << ( tmp_15_reg_1186 );

    SC_METHOD(thread_p_Val2_120_mux_fu_1132_p3);
    sensitive << ( brmerge_i_i7_fu_1114_p2 );
    sensitive << ( p_Val2_28_fu_1093_p3 );

    SC_METHOD(thread_p_Val2_12_fu_293_p2);
    sensitive << ( tmp_i_cast_fu_281_p1 );
    sensitive << ( tmp_i_cast_36_fu_289_p1 );

    SC_METHOD(thread_p_Val2_14_fu_461_p3);
    sensitive << ( tmp_s_reg_1233 );
    sensitive << ( qb_assign_5_reg_1269 );

    SC_METHOD(thread_p_Val2_15_fu_514_p3);
    sensitive << ( tmp7_fu_493_p2 );
    sensitive << ( p_Val2_97_mux_i_fu_498_p3 );
    sensitive << ( p_Val2_i4_fu_506_p3 );

    SC_METHOD(thread_p_Val2_17_fu_557_p2);
    sensitive << ( tmp_35_i_fu_546_p1 );
    sensitive << ( tmp_36_i5_fu_553_p1 );

    SC_METHOD(thread_p_Val2_18_fu_571_p1);
    sensitive << ( p_Val2_17_fu_557_p2 );

    SC_METHOD(thread_p_Val2_21_fu_706_p3);
    sensitive << ( grp_Compult_mpc_pso_fu_161_ap_return );

    SC_METHOD(thread_p_Val2_22_fu_721_p2);
    sensitive << ( tmp_4_fu_714_p1 );
    sensitive << ( tmp_5_fu_717_p1 );

    SC_METHOD(thread_p_Val2_23_fu_735_p1);
    sensitive << ( p_Val2_22_fu_721_p2 );

    SC_METHOD(thread_p_Val2_26_fu_890_p2);
    sensitive << ( p_Val2_25_reg_1378 );
    sensitive << ( tmp_9_fu_887_p1 );

    SC_METHOD(thread_p_Val2_28_fu_1093_p3);
    sensitive << ( tmp_53_reg_1468 );

    SC_METHOD(thread_p_Val2_3_i_fu_678_p3);
    sensitive << ( p_Val2_18_reg_1296 );
    sensitive << ( underflow_2_reg_1308 );

    SC_METHOD(thread_p_Val2_4_fu_1020_p3);
    sensitive << ( p_Val2_26_reg_1419 );
    sensitive << ( underflow_4_reg_1447 );

    SC_METHOD(thread_p_Val2_5_fu_1140_p3);
    sensitive << ( underflow_5_fu_1110_p2 );
    sensitive << ( p_Val2_28_fu_1093_p3 );

    SC_METHOD(thread_p_Val2_7_fu_246_p2);
    sensitive << ( p_Val2_6_reg_1156 );
    sensitive << ( tmp_1_fu_243_p1 );

    SC_METHOD(thread_p_Val2_8_fu_378_p0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( p_Val2_8_fu_378_p00 );

    SC_METHOD(thread_p_Val2_8_fu_378_p00);
    sensitive << ( ref_in_V );

    SC_METHOD(thread_p_Val2_8_fu_378_p2);
    sensitive << ( p_Val2_8_fu_378_p0 );

    SC_METHOD(thread_p_Val2_97_mux_i_fu_498_p3);
    sensitive << ( brmerge_i_i_i3_fu_487_p2 );
    sensitive << ( p_Val2_14_fu_461_p3 );

    SC_METHOD(thread_p_Val2_i4_fu_506_p3);
    sensitive << ( underflow_fu_482_p2 );
    sensitive << ( p_Val2_14_fu_461_p3 );

    SC_METHOD(thread_p_Val2_s_37_fu_778_p3);
    sensitive << ( p_Val2_23_reg_1348 );
    sensitive << ( underflow_3_fu_752_p2 );

    SC_METHOD(thread_p_Val2_s_fu_184_p0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_Val2_s_fu_184_p00 );

    SC_METHOD(thread_p_Val2_s_fu_184_p00);
    sensitive << ( y_in_V );

    SC_METHOD(thread_p_Val2_s_fu_184_p2);
    sensitive << ( p_Val2_s_fu_184_p0 );

    SC_METHOD(thread_p_not38_i_fu_1081_p2);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( p_Result_s_fu_1053_p4 );

    SC_METHOD(thread_p_not38_i_i_fu_623_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( p_Result_21_i_fu_583_p4 );

    SC_METHOD(thread_p_not_i5_i_fu_593_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( p_Result_21_i_fu_583_p4 );

    SC_METHOD(thread_p_not_i6_fu_1063_p2);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( p_Result_s_fu_1053_p4 );

    SC_METHOD(thread_p_not_i_fu_956_p2);
    sensitive << ( deleted_zeros_reg_1431 );

    SC_METHOD(thread_p_not_i_i_fu_431_p2);
    sensitive << ( tmp_38_reg_1238 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_phitmp8_fu_538_p3);
    sensitive << ( p_Val2_10_fu_525_p2 );
    sensitive << ( tmp_33_fu_530_p3 );

    SC_METHOD(thread_phitmp_fu_259_p3);
    sensitive << ( p_Val2_7_fu_246_p2 );
    sensitive << ( tmp_28_fu_251_p3 );

    SC_METHOD(thread_qb_assign_1_fu_238_p2);
    sensitive << ( qbit_reg_1161 );
    sensitive << ( r_i_i_fu_233_p2 );

    SC_METHOD(thread_qb_assign_3_fu_456_p2);
    sensitive << ( qbit_1_reg_1249 );
    sensitive << ( r_i_i2_fu_451_p2 );

    SC_METHOD(thread_qb_assign_5_fu_422_p2);
    sensitive << ( qbit_2_reg_1217 );
    sensitive << ( tmp_37_reg_1228 );

    SC_METHOD(thread_qb_assign_7_fu_882_p2);
    sensitive << ( qbit_3_reg_1383 );
    sensitive << ( r_i_i3_fu_877_p2 );

    SC_METHOD(thread_r_1_fu_446_p2);
    sensitive << ( tmp_30_reg_1254 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_r_2_fu_872_p2);
    sensitive << ( tmp_47_reg_1388 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_r_fu_228_p2);
    sensitive << ( tmp_25_reg_1166 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_r_i_i2_fu_451_p2);
    sensitive << ( tmp_32_reg_1264 );
    sensitive << ( r_1_fu_446_p2 );

    SC_METHOD(thread_r_i_i3_fu_877_p2);
    sensitive << ( tmp_49_reg_1398 );
    sensitive << ( r_2_fu_872_p2 );

    SC_METHOD(thread_r_i_i_fu_233_p2);
    sensitive << ( tmp_27_reg_1176 );
    sensitive << ( r_fu_228_p2 );

    SC_METHOD(thread_this_assign_s_fu_698_p3);
    sensitive << ( tmp_17_reg_1315 );

    SC_METHOD(thread_tmp7_fu_493_p2);
    sensitive << ( brmerge40_demorgan_i_i_reg_1279 );
    sensitive << ( tmp_34_i_fu_467_p2 );

    SC_METHOD(thread_tmp8_demorgan_fu_981_p2);
    sensitive << ( p_38_i_reg_1441 );
    sensitive << ( brmerge40_demorgan_i_fu_977_p2 );

    SC_METHOD(thread_tmp8_fu_986_p2);
    sensitive << ( tmp8_demorgan_fu_981_p2 );

    SC_METHOD(thread_tmp9_fu_1003_p2);
    sensitive << ( tmp_11_fu_966_p2 );
    sensitive << ( brmerge40_demorgan_i_fu_977_p2 );

    SC_METHOD(thread_tmp_10_fu_932_p2);
    sensitive << ( tmp_51_reg_1403 );

    SC_METHOD(thread_tmp_11_fu_966_p2);
    sensitive << ( signbit_1_reg_1371 );

    SC_METHOD(thread_tmp_12_fu_1100_p2);
    sensitive << ( isneg_3_reg_1462 );

    SC_METHOD(thread_tmp_15_fu_267_p3);
    sensitive << ( tmp_26_reg_1171 );
    sensitive << ( p_Val2_7_fu_246_p2 );
    sensitive << ( phitmp_fu_259_p3 );

    SC_METHOD(thread_tmp_16_fu_305_p3);
    sensitive << ( p_Val2_12_reg_1196 );

    SC_METHOD(thread_tmp_17_fu_646_p3);
    sensitive << ( tmp_31_reg_1259 );
    sensitive << ( p_Val2_10_fu_525_p2 );
    sensitive << ( phitmp8_fu_538_p3 );

    SC_METHOD(thread_tmp_1_fu_243_p1);
    sensitive << ( qb_assign_1_reg_1181 );

    SC_METHOD(thread_tmp_25_fu_208_p1);
    sensitive << ( p_Val2_s_fu_184_p2 );

    SC_METHOD(thread_tmp_28_fu_251_p3);
    sensitive << ( p_Val2_7_fu_246_p2 );

    SC_METHOD(thread_tmp_2_fu_903_p2);
    sensitive << ( newsignbit_4_fu_895_p3 );

    SC_METHOD(thread_tmp_30_fu_402_p1);
    sensitive << ( p_Val2_8_fu_378_p2 );

    SC_METHOD(thread_tmp_33_fu_530_p3);
    sensitive << ( p_Val2_10_fu_525_p2 );

    SC_METHOD(thread_tmp_34_i_fu_467_p2);
    sensitive << ( signbit_reg_1211 );

    SC_METHOD(thread_tmp_35_i_fu_546_p1);
    sensitive << ( p_Val2_15_reg_1290 );

    SC_METHOD(thread_tmp_36_i5_fu_553_p1);
    sensitive << ( x2_2_V );

    SC_METHOD(thread_tmp_37_i6_fu_605_p2);
    sensitive << ( isneg_fu_563_p3 );

    SC_METHOD(thread_tmp_3_fu_522_p1);
    sensitive << ( qb_assign_3_reg_1285 );

    SC_METHOD(thread_tmp_47_fu_834_p1);
    sensitive << ( grp_fu_802_p2 );

    SC_METHOD(thread_tmp_4_fu_714_p1);
    sensitive << ( u_V );

    SC_METHOD(thread_tmp_53_fu_1041_p1);
    sensitive << ( u_out_V_fu_1026_p3 );

    SC_METHOD(thread_tmp_5_fu_717_p1);
    sensitive << ( p_Val2_21_fu_706_p3 );

    SC_METHOD(thread_tmp_6_fu_747_p2);
    sensitive << ( newsignbit_3_reg_1354 );

    SC_METHOD(thread_tmp_7_fu_785_p3);
    sensitive << ( brmerge_fu_766_p2 );
    sensitive << ( p_Val2_115_mux_fu_771_p3 );
    sensitive << ( p_Val2_s_37_fu_778_p3 );

    SC_METHOD(thread_tmp_9_fu_887_p1);
    sensitive << ( qb_assign_7_reg_1414 );

    SC_METHOD(thread_tmp_fu_477_p2);
    sensitive << ( brmerge40_demorgan_i_i_reg_1279 );

    SC_METHOD(thread_tmp_i_cast_36_fu_289_p1);
    sensitive << ( x1_1_V );

    SC_METHOD(thread_tmp_i_cast_fu_281_p1);
    sensitive << ( p_Val2_11_fu_274_p3 );

    SC_METHOD(thread_u_out_V_fu_1026_p3);
    sensitive << ( underflow_17_not_reg_1457 );
    sensitive << ( p_Val2_118_mux_fu_1014_p3 );
    sensitive << ( p_Val2_4_fu_1020_p3 );

    SC_METHOD(thread_underflow_16_not_i_fu_661_p2);
    sensitive << ( underflow_2_reg_1308 );

    SC_METHOD(thread_underflow_17_not_fu_1009_p2);
    sensitive << ( p_38_i_reg_1441 );
    sensitive << ( tmp9_fu_1003_p2 );

    SC_METHOD(thread_underflow_18_not_fu_1120_p2);
    sensitive << ( underflow_5_fu_1110_p2 );

    SC_METHOD(thread_underflow_2_fu_635_p2);
    sensitive << ( isneg_fu_563_p3 );
    sensitive << ( brmerge39_i_i_fu_629_p2 );

    SC_METHOD(thread_underflow_3_fu_752_p2);
    sensitive << ( isneg_2_reg_1341 );
    sensitive << ( tmp_6_fu_747_p2 );

    SC_METHOD(thread_underflow_4_fu_992_p2);
    sensitive << ( signbit_1_reg_1371 );
    sensitive << ( tmp8_fu_986_p2 );

    SC_METHOD(thread_underflow_5_fu_1110_p2);
    sensitive << ( isneg_3_reg_1462 );
    sensitive << ( brmerge39_i_reg_1478 );

    SC_METHOD(thread_underflow_fu_482_p2);
    sensitive << ( signbit_reg_1211 );
    sensitive << ( tmp_fu_477_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_Compult_mpc_pso_fu_161_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000000000000000001";
    x1_1_V = "0000000000000000000000000000";
    x2_2_V = "00000000000000000000000000000000";
    u_V = "000000000000000000000000000000";
    grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Compult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, y_in_V, "(port)y_in_V");
    sc_trace(mVcdFile, ref_in_V, "(port)ref_in_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_40, "ap_sig_bdd_40");
    sc_trace(mVcdFile, x1_1_V, "x1_1_V");
    sc_trace(mVcdFile, x2_2_V, "x2_2_V");
    sc_trace(mVcdFile, u_V, "u_V");
    sc_trace(mVcdFile, p_Val2_6_reg_1156, "p_Val2_6_reg_1156");
    sc_trace(mVcdFile, qbit_reg_1161, "qbit_reg_1161");
    sc_trace(mVcdFile, tmp_25_fu_208_p1, "tmp_25_fu_208_p1");
    sc_trace(mVcdFile, tmp_25_reg_1166, "tmp_25_reg_1166");
    sc_trace(mVcdFile, tmp_26_reg_1171, "tmp_26_reg_1171");
    sc_trace(mVcdFile, tmp_27_reg_1176, "tmp_27_reg_1176");
    sc_trace(mVcdFile, qb_assign_1_fu_238_p2, "qb_assign_1_fu_238_p2");
    sc_trace(mVcdFile, qb_assign_1_reg_1181, "qb_assign_1_reg_1181");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_75, "ap_sig_bdd_75");
    sc_trace(mVcdFile, tmp_15_fu_267_p3, "tmp_15_fu_267_p3");
    sc_trace(mVcdFile, tmp_15_reg_1186, "tmp_15_reg_1186");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_84, "ap_sig_bdd_84");
    sc_trace(mVcdFile, p_Val2_11_fu_274_p3, "p_Val2_11_fu_274_p3");
    sc_trace(mVcdFile, p_Val2_11_reg_1191, "p_Val2_11_reg_1191");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, p_Val2_12_fu_293_p2, "p_Val2_12_fu_293_p2");
    sc_trace(mVcdFile, p_Val2_12_reg_1196, "p_Val2_12_reg_1196");
    sc_trace(mVcdFile, tmp_16_fu_305_p3, "tmp_16_fu_305_p3");
    sc_trace(mVcdFile, tmp_16_reg_1201, "tmp_16_reg_1201");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_104, "ap_sig_bdd_104");
    sc_trace(mVcdFile, signbit_reg_1211, "signbit_reg_1211");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_115, "ap_sig_bdd_115");
    sc_trace(mVcdFile, qbit_2_reg_1217, "qbit_2_reg_1217");
    sc_trace(mVcdFile, newsignbit_reg_1222, "newsignbit_reg_1222");
    sc_trace(mVcdFile, tmp_37_reg_1228, "tmp_37_reg_1228");
    sc_trace(mVcdFile, tmp_s_reg_1233, "tmp_s_reg_1233");
    sc_trace(mVcdFile, tmp_38_reg_1238, "tmp_38_reg_1238");
    sc_trace(mVcdFile, p_Val2_9_reg_1244, "p_Val2_9_reg_1244");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_134, "ap_sig_bdd_134");
    sc_trace(mVcdFile, qbit_1_reg_1249, "qbit_1_reg_1249");
    sc_trace(mVcdFile, tmp_30_fu_402_p1, "tmp_30_fu_402_p1");
    sc_trace(mVcdFile, tmp_30_reg_1254, "tmp_30_reg_1254");
    sc_trace(mVcdFile, tmp_31_reg_1259, "tmp_31_reg_1259");
    sc_trace(mVcdFile, tmp_32_reg_1264, "tmp_32_reg_1264");
    sc_trace(mVcdFile, qb_assign_5_fu_422_p2, "qb_assign_5_fu_422_p2");
    sc_trace(mVcdFile, qb_assign_5_reg_1269, "qb_assign_5_reg_1269");
    sc_trace(mVcdFile, brmerge_i_i2_fu_436_p2, "brmerge_i_i2_fu_436_p2");
    sc_trace(mVcdFile, brmerge_i_i2_reg_1274, "brmerge_i_i2_reg_1274");
    sc_trace(mVcdFile, brmerge40_demorgan_i_i_fu_441_p2, "brmerge40_demorgan_i_i_fu_441_p2");
    sc_trace(mVcdFile, brmerge40_demorgan_i_i_reg_1279, "brmerge40_demorgan_i_i_reg_1279");
    sc_trace(mVcdFile, qb_assign_3_fu_456_p2, "qb_assign_3_fu_456_p2");
    sc_trace(mVcdFile, qb_assign_3_reg_1285, "qb_assign_3_reg_1285");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_157, "ap_sig_bdd_157");
    sc_trace(mVcdFile, p_Val2_15_fu_514_p3, "p_Val2_15_fu_514_p3");
    sc_trace(mVcdFile, p_Val2_15_reg_1290, "p_Val2_15_reg_1290");
    sc_trace(mVcdFile, p_Val2_18_fu_571_p1, "p_Val2_18_fu_571_p1");
    sc_trace(mVcdFile, p_Val2_18_reg_1296, "p_Val2_18_reg_1296");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_168, "ap_sig_bdd_168");
    sc_trace(mVcdFile, overflow_2_fu_611_p2, "overflow_2_fu_611_p2");
    sc_trace(mVcdFile, overflow_2_reg_1302, "overflow_2_reg_1302");
    sc_trace(mVcdFile, underflow_2_fu_635_p2, "underflow_2_fu_635_p2");
    sc_trace(mVcdFile, underflow_2_reg_1308, "underflow_2_reg_1308");
    sc_trace(mVcdFile, tmp_17_fu_646_p3, "tmp_17_fu_646_p3");
    sc_trace(mVcdFile, tmp_17_reg_1315, "tmp_17_reg_1315");
    sc_trace(mVcdFile, dx1_V_fu_653_p1, "dx1_V_fu_653_p1");
    sc_trace(mVcdFile, dx1_V_reg_1320, "dx1_V_reg_1320");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_183, "ap_sig_bdd_183");
    sc_trace(mVcdFile, dx2_V_fu_684_p3, "dx2_V_fu_684_p3");
    sc_trace(mVcdFile, dx2_V_reg_1325, "dx2_V_reg_1325");
    sc_trace(mVcdFile, this_assign_s_fu_698_p3, "this_assign_s_fu_698_p3");
    sc_trace(mVcdFile, this_assign_s_reg_1336, "this_assign_s_reg_1336");
    sc_trace(mVcdFile, isneg_2_reg_1341, "isneg_2_reg_1341");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_198, "ap_sig_bdd_198");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_done, "grp_Compult_mpc_pso_fu_161_ap_done");
    sc_trace(mVcdFile, p_Val2_23_fu_735_p1, "p_Val2_23_fu_735_p1");
    sc_trace(mVcdFile, p_Val2_23_reg_1348, "p_Val2_23_reg_1348");
    sc_trace(mVcdFile, newsignbit_3_reg_1354, "newsignbit_3_reg_1354");
    sc_trace(mVcdFile, tmp_7_fu_785_p3, "tmp_7_fu_785_p3");
    sc_trace(mVcdFile, tmp_7_reg_1361, "tmp_7_reg_1361");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_215, "ap_sig_bdd_215");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_224, "ap_sig_bdd_224");
    sc_trace(mVcdFile, signbit_1_reg_1371, "signbit_1_reg_1371");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_233, "ap_sig_bdd_233");
    sc_trace(mVcdFile, p_Val2_25_reg_1378, "p_Val2_25_reg_1378");
    sc_trace(mVcdFile, qbit_3_reg_1383, "qbit_3_reg_1383");
    sc_trace(mVcdFile, tmp_47_fu_834_p1, "tmp_47_fu_834_p1");
    sc_trace(mVcdFile, tmp_47_reg_1388, "tmp_47_reg_1388");
    sc_trace(mVcdFile, tmp_48_reg_1393, "tmp_48_reg_1393");
    sc_trace(mVcdFile, tmp_49_reg_1398, "tmp_49_reg_1398");
    sc_trace(mVcdFile, tmp_51_reg_1403, "tmp_51_reg_1403");
    sc_trace(mVcdFile, tmp_8_reg_1408, "tmp_8_reg_1408");
    sc_trace(mVcdFile, qb_assign_7_fu_882_p2, "qb_assign_7_fu_882_p2");
    sc_trace(mVcdFile, qb_assign_7_reg_1414, "qb_assign_7_reg_1414");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_256, "ap_sig_bdd_256");
    sc_trace(mVcdFile, p_Val2_26_fu_890_p2, "p_Val2_26_fu_890_p2");
    sc_trace(mVcdFile, p_Val2_26_reg_1419, "p_Val2_26_reg_1419");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_265, "ap_sig_bdd_265");
    sc_trace(mVcdFile, newsignbit_4_fu_895_p3, "newsignbit_4_fu_895_p3");
    sc_trace(mVcdFile, newsignbit_4_reg_1425, "newsignbit_4_reg_1425");
    sc_trace(mVcdFile, deleted_zeros_fu_924_p3, "deleted_zeros_fu_924_p3");
    sc_trace(mVcdFile, deleted_zeros_reg_1431, "deleted_zeros_reg_1431");
    sc_trace(mVcdFile, deleted_ones_fu_942_p3, "deleted_ones_fu_942_p3");
    sc_trace(mVcdFile, deleted_ones_reg_1436, "deleted_ones_reg_1436");
    sc_trace(mVcdFile, p_38_i_fu_950_p2, "p_38_i_fu_950_p2");
    sc_trace(mVcdFile, p_38_i_reg_1441, "p_38_i_reg_1441");
    sc_trace(mVcdFile, underflow_4_fu_992_p2, "underflow_4_fu_992_p2");
    sc_trace(mVcdFile, underflow_4_reg_1447, "underflow_4_reg_1447");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_bdd_282, "ap_sig_bdd_282");
    sc_trace(mVcdFile, brmerge_i_i6_fu_997_p2, "brmerge_i_i6_fu_997_p2");
    sc_trace(mVcdFile, brmerge_i_i6_reg_1452, "brmerge_i_i6_reg_1452");
    sc_trace(mVcdFile, underflow_17_not_fu_1009_p2, "underflow_17_not_fu_1009_p2");
    sc_trace(mVcdFile, underflow_17_not_reg_1457, "underflow_17_not_reg_1457");
    sc_trace(mVcdFile, isneg_3_reg_1462, "isneg_3_reg_1462");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_295, "ap_sig_bdd_295");
    sc_trace(mVcdFile, tmp_53_fu_1041_p1, "tmp_53_fu_1041_p1");
    sc_trace(mVcdFile, tmp_53_reg_1468, "tmp_53_reg_1468");
    sc_trace(mVcdFile, brmerge_i8_fu_1069_p2, "brmerge_i8_fu_1069_p2");
    sc_trace(mVcdFile, brmerge_i8_reg_1473, "brmerge_i8_reg_1473");
    sc_trace(mVcdFile, brmerge39_i_fu_1087_p2, "brmerge39_i_fu_1087_p2");
    sc_trace(mVcdFile, brmerge39_i_reg_1478, "brmerge39_i_reg_1478");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_start, "grp_Compult_mpc_pso_fu_161_ap_start");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_idle, "grp_Compult_mpc_pso_fu_161_ap_idle");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_ready, "grp_Compult_mpc_pso_fu_161_ap_ready");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_dx1_in_V, "grp_Compult_mpc_pso_fu_161_dx1_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_dx2_in_V, "grp_Compult_mpc_pso_fu_161_dx2_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_y_in_V, "grp_Compult_mpc_pso_fu_161_y_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_u_in_V, "grp_Compult_mpc_pso_fu_161_u_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ref_in_V, "grp_Compult_mpc_pso_fu_161_ref_in_V");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_return, "grp_Compult_mpc_pso_fu_161_ap_return");
    sc_trace(mVcdFile, grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg, "grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg");
    sc_trace(mVcdFile, p_Val2_s_fu_184_p0, "p_Val2_s_fu_184_p0");
    sc_trace(mVcdFile, p_Val2_s_fu_184_p2, "p_Val2_s_fu_184_p2");
    sc_trace(mVcdFile, r_fu_228_p2, "r_fu_228_p2");
    sc_trace(mVcdFile, r_i_i_fu_233_p2, "r_i_i_fu_233_p2");
    sc_trace(mVcdFile, tmp_1_fu_243_p1, "tmp_1_fu_243_p1");
    sc_trace(mVcdFile, p_Val2_7_fu_246_p2, "p_Val2_7_fu_246_p2");
    sc_trace(mVcdFile, tmp_28_fu_251_p3, "tmp_28_fu_251_p3");
    sc_trace(mVcdFile, phitmp_fu_259_p3, "phitmp_fu_259_p3");
    sc_trace(mVcdFile, tmp_i_cast_fu_281_p1, "tmp_i_cast_fu_281_p1");
    sc_trace(mVcdFile, tmp_i_cast_36_fu_289_p1, "tmp_i_cast_36_fu_289_p1");
    sc_trace(mVcdFile, grp_fu_316_p0, "grp_fu_316_p0");
    sc_trace(mVcdFile, grp_fu_316_p1, "grp_fu_316_p1");
    sc_trace(mVcdFile, grp_fu_316_p2, "grp_fu_316_p2");
    sc_trace(mVcdFile, p_Val2_8_fu_378_p0, "p_Val2_8_fu_378_p0");
    sc_trace(mVcdFile, p_Val2_8_fu_378_p2, "p_Val2_8_fu_378_p2");
    sc_trace(mVcdFile, p_not_i_i_fu_431_p2, "p_not_i_i_fu_431_p2");
    sc_trace(mVcdFile, Range1_all_ones_3_fu_426_p2, "Range1_all_ones_3_fu_426_p2");
    sc_trace(mVcdFile, r_1_fu_446_p2, "r_1_fu_446_p2");
    sc_trace(mVcdFile, r_i_i2_fu_451_p2, "r_i_i2_fu_451_p2");
    sc_trace(mVcdFile, tmp_34_i_fu_467_p2, "tmp_34_i_fu_467_p2");
    sc_trace(mVcdFile, tmp_fu_477_p2, "tmp_fu_477_p2");
    sc_trace(mVcdFile, underflow_fu_482_p2, "underflow_fu_482_p2");
    sc_trace(mVcdFile, overflow_fu_472_p2, "overflow_fu_472_p2");
    sc_trace(mVcdFile, brmerge_i_i_i3_fu_487_p2, "brmerge_i_i_i3_fu_487_p2");
    sc_trace(mVcdFile, p_Val2_14_fu_461_p3, "p_Val2_14_fu_461_p3");
    sc_trace(mVcdFile, tmp7_fu_493_p2, "tmp7_fu_493_p2");
    sc_trace(mVcdFile, p_Val2_97_mux_i_fu_498_p3, "p_Val2_97_mux_i_fu_498_p3");
    sc_trace(mVcdFile, p_Val2_i4_fu_506_p3, "p_Val2_i4_fu_506_p3");
    sc_trace(mVcdFile, tmp_3_fu_522_p1, "tmp_3_fu_522_p1");
    sc_trace(mVcdFile, p_Val2_10_fu_525_p2, "p_Val2_10_fu_525_p2");
    sc_trace(mVcdFile, tmp_33_fu_530_p3, "tmp_33_fu_530_p3");
    sc_trace(mVcdFile, tmp_35_i_fu_546_p1, "tmp_35_i_fu_546_p1");
    sc_trace(mVcdFile, tmp_36_i5_fu_553_p1, "tmp_36_i5_fu_553_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_557_p2, "p_Val2_17_fu_557_p2");
    sc_trace(mVcdFile, p_Result_21_i_fu_583_p4, "p_Result_21_i_fu_583_p4");
    sc_trace(mVcdFile, newsignbit_2_fu_575_p3, "newsignbit_2_fu_575_p3");
    sc_trace(mVcdFile, p_not_i5_i_fu_593_p2, "p_not_i5_i_fu_593_p2");
    sc_trace(mVcdFile, isneg_fu_563_p3, "isneg_fu_563_p3");
    sc_trace(mVcdFile, brmerge_i6_i_fu_599_p2, "brmerge_i6_i_fu_599_p2");
    sc_trace(mVcdFile, tmp_37_i6_fu_605_p2, "tmp_37_i6_fu_605_p2");
    sc_trace(mVcdFile, p_not38_i_i_fu_623_p2, "p_not38_i_i_fu_623_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_617_p2, "newsignbit_0_not_i_i_fu_617_p2");
    sc_trace(mVcdFile, brmerge39_i_i_fu_629_p2, "brmerge39_i_i_fu_629_p2");
    sc_trace(mVcdFile, phitmp8_fu_538_p3, "phitmp8_fu_538_p3");
    sc_trace(mVcdFile, underflow_16_not_i_fu_661_p2, "underflow_16_not_i_fu_661_p2");
    sc_trace(mVcdFile, brmerge_i_i5_i_fu_657_p2, "brmerge_i_i5_i_fu_657_p2");
    sc_trace(mVcdFile, brmerge2_i_fu_666_p2, "brmerge2_i_fu_666_p2");
    sc_trace(mVcdFile, p_Val2_101_mux_i_fu_671_p3, "p_Val2_101_mux_i_fu_671_p3");
    sc_trace(mVcdFile, p_Val2_3_i_fu_678_p3, "p_Val2_3_i_fu_678_p3");
    sc_trace(mVcdFile, p_Val2_21_fu_706_p3, "p_Val2_21_fu_706_p3");
    sc_trace(mVcdFile, tmp_4_fu_714_p1, "tmp_4_fu_714_p1");
    sc_trace(mVcdFile, tmp_5_fu_717_p1, "tmp_5_fu_717_p1");
    sc_trace(mVcdFile, p_Val2_22_fu_721_p2, "p_Val2_22_fu_721_p2");
    sc_trace(mVcdFile, tmp_6_fu_747_p2, "tmp_6_fu_747_p2");
    sc_trace(mVcdFile, isneg_not_fu_761_p2, "isneg_not_fu_761_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_757_p2, "brmerge_i_i_fu_757_p2");
    sc_trace(mVcdFile, underflow_3_fu_752_p2, "underflow_3_fu_752_p2");
    sc_trace(mVcdFile, brmerge_fu_766_p2, "brmerge_fu_766_p2");
    sc_trace(mVcdFile, p_Val2_115_mux_fu_771_p3, "p_Val2_115_mux_fu_771_p3");
    sc_trace(mVcdFile, p_Val2_s_37_fu_778_p3, "p_Val2_s_37_fu_778_p3");
    sc_trace(mVcdFile, grp_fu_802_p0, "grp_fu_802_p0");
    sc_trace(mVcdFile, grp_fu_802_p1, "grp_fu_802_p1");
    sc_trace(mVcdFile, grp_fu_802_p2, "grp_fu_802_p2");
    sc_trace(mVcdFile, r_2_fu_872_p2, "r_2_fu_872_p2");
    sc_trace(mVcdFile, r_i_i3_fu_877_p2, "r_i_i3_fu_877_p2");
    sc_trace(mVcdFile, tmp_9_fu_887_p1, "tmp_9_fu_887_p1");
    sc_trace(mVcdFile, tmp_2_fu_903_p2, "tmp_2_fu_903_p2");
    sc_trace(mVcdFile, carry_fu_909_p2, "carry_fu_909_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_914_p2, "Range1_all_ones_fu_914_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_919_p2, "Range1_all_zeros_fu_919_p2");
    sc_trace(mVcdFile, tmp_10_fu_932_p2, "tmp_10_fu_932_p2");
    sc_trace(mVcdFile, p_41_i_fu_937_p2, "p_41_i_fu_937_p2");
    sc_trace(mVcdFile, p_not_i_fu_956_p2, "p_not_i_fu_956_p2");
    sc_trace(mVcdFile, brmerge_i7_fu_961_p2, "brmerge_i7_fu_961_p2");
    sc_trace(mVcdFile, tmp_11_fu_966_p2, "tmp_11_fu_966_p2");
    sc_trace(mVcdFile, brmerge40_demorgan_i_fu_977_p2, "brmerge40_demorgan_i_fu_977_p2");
    sc_trace(mVcdFile, tmp8_demorgan_fu_981_p2, "tmp8_demorgan_fu_981_p2");
    sc_trace(mVcdFile, tmp8_fu_986_p2, "tmp8_fu_986_p2");
    sc_trace(mVcdFile, overflow_3_fu_971_p2, "overflow_3_fu_971_p2");
    sc_trace(mVcdFile, tmp9_fu_1003_p2, "tmp9_fu_1003_p2");
    sc_trace(mVcdFile, p_Val2_118_mux_fu_1014_p3, "p_Val2_118_mux_fu_1014_p3");
    sc_trace(mVcdFile, p_Val2_4_fu_1020_p3, "p_Val2_4_fu_1020_p3");
    sc_trace(mVcdFile, u_out_V_fu_1026_p3, "u_out_V_fu_1026_p3");
    sc_trace(mVcdFile, p_Result_s_fu_1053_p4, "p_Result_s_fu_1053_p4");
    sc_trace(mVcdFile, newsignbit_5_fu_1045_p3, "newsignbit_5_fu_1045_p3");
    sc_trace(mVcdFile, p_not_i6_fu_1063_p2, "p_not_i6_fu_1063_p2");
    sc_trace(mVcdFile, p_not38_i_fu_1081_p2, "p_not38_i_fu_1081_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_fu_1075_p2, "newsignbit_0_not_i_fu_1075_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_bdd_774, "ap_sig_bdd_774");
    sc_trace(mVcdFile, tmp_12_fu_1100_p2, "tmp_12_fu_1100_p2");
    sc_trace(mVcdFile, underflow_5_fu_1110_p2, "underflow_5_fu_1110_p2");
    sc_trace(mVcdFile, overflow_4_fu_1105_p2, "overflow_4_fu_1105_p2");
    sc_trace(mVcdFile, underflow_18_not_fu_1120_p2, "underflow_18_not_fu_1120_p2");
    sc_trace(mVcdFile, brmerge_i_i7_fu_1114_p2, "brmerge_i_i7_fu_1114_p2");
    sc_trace(mVcdFile, p_Val2_28_fu_1093_p3, "p_Val2_28_fu_1093_p3");
    sc_trace(mVcdFile, brmerge7_fu_1126_p2, "brmerge7_fu_1126_p2");
    sc_trace(mVcdFile, p_Val2_120_mux_fu_1132_p3, "p_Val2_120_mux_fu_1132_p3");
    sc_trace(mVcdFile, p_Val2_5_fu_1140_p3, "p_Val2_5_fu_1140_p3");
    sc_trace(mVcdFile, grp_fu_316_ce, "grp_fu_316_ce");
    sc_trace(mVcdFile, grp_fu_802_ce, "grp_fu_802_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, p_Val2_8_fu_378_p00, "p_Val2_8_fu_378_p00");
    sc_trace(mVcdFile, p_Val2_s_fu_184_p00, "p_Val2_s_fu_184_p00");
#endif

    }
    mHdltvinHandle.open("Compult.hdltvin.dat");
    mHdltvoutHandle.open("Compult.hdltvout.dat");
}

Compult::~Compult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_Compult_mpc_pso_fu_161;
    delete Compult_mul_31s_10ns_41_3_U59;
    delete Compult_mul_30s_26ns_55_6_U60;
}

void Compult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
            grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Compult_mpc_pso_fu_161_ap_ready.read())) {
            grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        brmerge39_i_reg_1478 = brmerge39_i_fu_1087_p2.read();
        brmerge_i8_reg_1473 = brmerge_i8_fu_1069_p2.read();
        isneg_3_reg_1462 = u_out_V_fu_1026_p3.read().range(15, 15);
        tmp_53_reg_1468 = tmp_53_fu_1041_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        brmerge40_demorgan_i_i_reg_1279 = brmerge40_demorgan_i_i_fu_441_p2.read();
        brmerge_i_i2_reg_1274 = brmerge_i_i2_fu_436_p2.read();
        p_Val2_9_reg_1244 = p_Val2_8_fu_378_p2.read().range(34, 19);
        qb_assign_5_reg_1269 = qb_assign_5_fu_422_p2.read();
        qbit_1_reg_1249 = p_Val2_8_fu_378_p2.read().range(18, 18);
        tmp_30_reg_1254 = tmp_30_fu_402_p1.read();
        tmp_31_reg_1259 = p_Val2_8_fu_378_p2.read().range(34, 34);
        tmp_32_reg_1264 = p_Val2_8_fu_378_p2.read().range(19, 19);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        brmerge_i_i6_reg_1452 = brmerge_i_i6_fu_997_p2.read();
        underflow_17_not_reg_1457 = underflow_17_not_fu_1009_p2.read();
        underflow_4_reg_1447 = underflow_4_fu_992_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        deleted_ones_reg_1436 = deleted_ones_fu_942_p3.read();
        deleted_zeros_reg_1431 = deleted_zeros_fu_924_p3.read();
        newsignbit_4_reg_1425 = p_Val2_26_fu_890_p2.read().range(15, 15);
        p_38_i_reg_1441 = p_38_i_fu_950_p2.read();
        p_Val2_26_reg_1419 = p_Val2_26_fu_890_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        dx1_V_reg_1320 = dx1_V_fu_653_p1.read();
        dx2_V_reg_1325 = dx2_V_fu_684_p3.read();
        this_assign_s_reg_1336 = this_assign_s_fu_698_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_Compult_mpc_pso_fu_161_ap_done.read()))) {
        isneg_2_reg_1341 = p_Val2_22_fu_721_p2.read().range(30, 30);
        newsignbit_3_reg_1354 = p_Val2_22_fu_721_p2.read().range(29, 29);
        p_Val2_23_reg_1348 = p_Val2_23_fu_735_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        newsignbit_reg_1222 = grp_fu_316_p2.read().range(33, 33);
        qbit_2_reg_1217 = grp_fu_316_p2.read().range(1, 1);
        signbit_reg_1211 = grp_fu_316_p2.read().range(40, 40);
        tmp_37_reg_1228 = grp_fu_316_p2.read().range(2, 2);
        tmp_38_reg_1238 = grp_fu_316_p2.read().range(40, 34);
        tmp_s_reg_1233 = grp_fu_316_p2.read().range(33, 3);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        overflow_2_reg_1302 = overflow_2_fu_611_p2.read();
        p_Val2_18_reg_1296 = p_Val2_18_fu_571_p1.read();
        tmp_17_reg_1315 = tmp_17_fu_646_p3.read();
        underflow_2_reg_1308 = underflow_2_fu_635_p2.read();
        x2_2_V = p_Val2_15_reg_1290.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        p_Val2_11_reg_1191 = p_Val2_11_fu_274_p3.read();
        p_Val2_12_reg_1196 = p_Val2_12_fu_293_p2.read();
        x1_1_V = p_Val2_11_fu_274_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        p_Val2_15_reg_1290 = p_Val2_15_fu_514_p3.read();
        qb_assign_3_reg_1285 = qb_assign_3_fu_456_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        p_Val2_25_reg_1378 = grp_fu_802_p2.read().range(52, 37);
        qbit_3_reg_1383 = grp_fu_802_p2.read().range(36, 36);
        signbit_1_reg_1371 = grp_fu_802_p2.read().range(54, 54);
        tmp_47_reg_1388 = tmp_47_fu_834_p1.read();
        tmp_48_reg_1393 = grp_fu_802_p2.read().range(52, 52);
        tmp_49_reg_1398 = grp_fu_802_p2.read().range(37, 37);
        tmp_51_reg_1403 = grp_fu_802_p2.read().range(53, 53);
        tmp_8_reg_1408 = grp_fu_802_p2.read().range(54, 53);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_Val2_6_reg_1156 = p_Val2_s_fu_184_p2.read().range(34, 19);
        qbit_reg_1161 = p_Val2_s_fu_184_p2.read().range(18, 18);
        tmp_25_reg_1166 = tmp_25_fu_208_p1.read();
        tmp_26_reg_1171 = p_Val2_s_fu_184_p2.read().range(34, 34);
        tmp_27_reg_1176 = p_Val2_s_fu_184_p2.read().range(19, 19);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        qb_assign_1_reg_1181 = qb_assign_1_fu_238_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        qb_assign_7_reg_1414 = qb_assign_7_fu_882_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        tmp_15_reg_1186 = tmp_15_fu_267_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_16_reg_1201 = tmp_16_fu_305_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        tmp_7_reg_1361 = tmp_7_fu_785_p3.read();
        u_V = tmp_7_fu_785_p3.read();
    }
}

void Compult::thread_Range1_all_ones_3_fu_426_p2() {
    Range1_all_ones_3_fu_426_p2 = (!tmp_38_reg_1238.read().is_01() || !ap_const_lv7_7F.is_01())? sc_lv<1>(): sc_lv<1>(tmp_38_reg_1238.read() == ap_const_lv7_7F);
}

void Compult::thread_Range1_all_ones_fu_914_p2() {
    Range1_all_ones_fu_914_p2 = (!tmp_8_reg_1408.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_reg_1408.read() == ap_const_lv2_3);
}

void Compult::thread_Range1_all_zeros_fu_919_p2() {
    Range1_all_zeros_fu_919_p2 = (!tmp_8_reg_1408.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_reg_1408.read() == ap_const_lv2_0);
}

void Compult::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Compult::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Compult::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Compult::thread_ap_return() {
    ap_return = (!brmerge7_fu_1126_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge7_fu_1126_p2.read()[0].to_bool())? p_Val2_120_mux_fu_1132_p3.read(): p_Val2_5_fu_1140_p3.read());
}

void Compult::thread_ap_sig_bdd_104() {
    ap_sig_bdd_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void Compult::thread_ap_sig_bdd_115() {
    ap_sig_bdd_115 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void Compult::thread_ap_sig_bdd_134() {
    ap_sig_bdd_134 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void Compult::thread_ap_sig_bdd_157() {
    ap_sig_bdd_157 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void Compult::thread_ap_sig_bdd_168() {
    ap_sig_bdd_168 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void Compult::thread_ap_sig_bdd_183() {
    ap_sig_bdd_183 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void Compult::thread_ap_sig_bdd_198() {
    ap_sig_bdd_198 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void Compult::thread_ap_sig_bdd_215() {
    ap_sig_bdd_215 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void Compult::thread_ap_sig_bdd_224() {
    ap_sig_bdd_224 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void Compult::thread_ap_sig_bdd_233() {
    ap_sig_bdd_233 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void Compult::thread_ap_sig_bdd_256() {
    ap_sig_bdd_256 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void Compult::thread_ap_sig_bdd_265() {
    ap_sig_bdd_265 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void Compult::thread_ap_sig_bdd_282() {
    ap_sig_bdd_282 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void Compult::thread_ap_sig_bdd_295() {
    ap_sig_bdd_295 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void Compult::thread_ap_sig_bdd_40() {
    ap_sig_bdd_40 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void Compult::thread_ap_sig_bdd_75() {
    ap_sig_bdd_75 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void Compult::thread_ap_sig_bdd_774() {
    ap_sig_bdd_774 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void Compult::thread_ap_sig_bdd_84() {
    ap_sig_bdd_84 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void Compult::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void Compult::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_168.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_183.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_198.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_215.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_224.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_233.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_40.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_256.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_265.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_bdd_282.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_295.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_bdd_774.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_75.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_84.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_93.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_104.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_115.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_134.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void Compult::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_157.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void Compult::thread_brmerge2_i_fu_666_p2() {
    brmerge2_i_fu_666_p2 = (overflow_2_reg_1302.read() | underflow_16_not_i_fu_661_p2.read());
}

void Compult::thread_brmerge39_i_fu_1087_p2() {
    brmerge39_i_fu_1087_p2 = (p_not38_i_fu_1081_p2.read() | newsignbit_0_not_i_fu_1075_p2.read());
}

void Compult::thread_brmerge39_i_i_fu_629_p2() {
    brmerge39_i_i_fu_629_p2 = (p_not38_i_i_fu_623_p2.read() | newsignbit_0_not_i_i_fu_617_p2.read());
}

void Compult::thread_brmerge40_demorgan_i_fu_977_p2() {
    brmerge40_demorgan_i_fu_977_p2 = (newsignbit_4_reg_1425.read() & deleted_ones_reg_1436.read());
}

void Compult::thread_brmerge40_demorgan_i_i_fu_441_p2() {
    brmerge40_demorgan_i_i_fu_441_p2 = (newsignbit_reg_1222.read() & Range1_all_ones_3_fu_426_p2.read());
}

void Compult::thread_brmerge7_fu_1126_p2() {
    brmerge7_fu_1126_p2 = (overflow_4_fu_1105_p2.read() | underflow_18_not_fu_1120_p2.read());
}

void Compult::thread_brmerge_fu_766_p2() {
    brmerge_fu_766_p2 = (newsignbit_3_reg_1354.read() | isneg_not_fu_761_p2.read());
}

void Compult::thread_brmerge_i6_i_fu_599_p2() {
    brmerge_i6_i_fu_599_p2 = (newsignbit_2_fu_575_p3.read() | p_not_i5_i_fu_593_p2.read());
}

void Compult::thread_brmerge_i7_fu_961_p2() {
    brmerge_i7_fu_961_p2 = (newsignbit_4_reg_1425.read() | p_not_i_fu_956_p2.read());
}

void Compult::thread_brmerge_i8_fu_1069_p2() {
    brmerge_i8_fu_1069_p2 = (newsignbit_5_fu_1045_p3.read() | p_not_i6_fu_1063_p2.read());
}

void Compult::thread_brmerge_i_i2_fu_436_p2() {
    brmerge_i_i2_fu_436_p2 = (newsignbit_reg_1222.read() | p_not_i_i_fu_431_p2.read());
}

void Compult::thread_brmerge_i_i5_i_fu_657_p2() {
    brmerge_i_i5_i_fu_657_p2 = (underflow_2_reg_1308.read() | overflow_2_reg_1302.read());
}

void Compult::thread_brmerge_i_i6_fu_997_p2() {
    brmerge_i_i6_fu_997_p2 = (underflow_4_fu_992_p2.read() | overflow_3_fu_971_p2.read());
}

void Compult::thread_brmerge_i_i7_fu_1114_p2() {
    brmerge_i_i7_fu_1114_p2 = (underflow_5_fu_1110_p2.read() | overflow_4_fu_1105_p2.read());
}

void Compult::thread_brmerge_i_i_fu_757_p2() {
    brmerge_i_i_fu_757_p2 = (isneg_2_reg_1341.read() ^ newsignbit_3_reg_1354.read());
}

void Compult::thread_brmerge_i_i_i3_fu_487_p2() {
    brmerge_i_i_i3_fu_487_p2 = (underflow_fu_482_p2.read() | overflow_fu_472_p2.read());
}

void Compult::thread_carry_fu_909_p2() {
    carry_fu_909_p2 = (tmp_48_reg_1393.read() & tmp_2_fu_903_p2.read());
}

void Compult::thread_deleted_ones_fu_942_p3() {
    deleted_ones_fu_942_p3 = (!carry_fu_909_p2.read()[0].is_01())? sc_lv<1>(): ((carry_fu_909_p2.read()[0].to_bool())? p_41_i_fu_937_p2.read(): Range1_all_ones_fu_914_p2.read());
}

void Compult::thread_deleted_zeros_fu_924_p3() {
    deleted_zeros_fu_924_p3 = (!carry_fu_909_p2.read()[0].is_01())? sc_lv<1>(): ((carry_fu_909_p2.read()[0].to_bool())? Range1_all_ones_fu_914_p2.read(): Range1_all_zeros_fu_919_p2.read());
}

void Compult::thread_dx1_V_fu_653_p1() {
    dx1_V_fu_653_p1 = esl_sext<32,31>(tmp_16_reg_1201.read());
}

void Compult::thread_dx2_V_fu_684_p3() {
    dx2_V_fu_684_p3 = (!brmerge2_i_fu_666_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge2_i_fu_666_p2.read()[0].to_bool())? p_Val2_101_mux_i_fu_671_p3.read(): p_Val2_3_i_fu_678_p3.read());
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_ap_start() {
    grp_Compult_mpc_pso_fu_161_ap_start = grp_Compult_mpc_pso_fu_161_ap_start_ap_start_reg.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_dx1_in_V() {
    grp_Compult_mpc_pso_fu_161_dx1_in_V = dx1_V_reg_1320.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_dx2_in_V() {
    grp_Compult_mpc_pso_fu_161_dx2_in_V = dx2_V_reg_1325.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_ref_in_V() {
    grp_Compult_mpc_pso_fu_161_ref_in_V = this_assign_s_reg_1336.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_u_in_V() {
    grp_Compult_mpc_pso_fu_161_u_in_V = u_V.read();
}

void Compult::thread_grp_Compult_mpc_pso_fu_161_y_in_V() {
    grp_Compult_mpc_pso_fu_161_y_in_V = p_Val2_11_reg_1191.read();
}

void Compult::thread_grp_fu_316_ce() {
    grp_fu_316_ce = ap_const_logic_1;
}

void Compult::thread_grp_fu_316_p0() {
    grp_fu_316_p0 = tmp_16_fu_305_p3.read();
}

void Compult::thread_grp_fu_316_p1() {
    grp_fu_316_p1 =  (sc_lv<10>) (ap_const_lv41_1F4);
}

void Compult::thread_grp_fu_802_ce() {
    grp_fu_802_ce = ap_const_logic_1;
}

void Compult::thread_grp_fu_802_p0() {
    grp_fu_802_p0 = tmp_7_reg_1361.read();
}

void Compult::thread_grp_fu_802_p1() {
    grp_fu_802_p1 =  (sc_lv<26>) (ap_const_lv55_1D4C000);
}

void Compult::thread_isneg_fu_563_p3() {
    isneg_fu_563_p3 = p_Val2_17_fu_557_p2.read().range(32, 32);
}

void Compult::thread_isneg_not_fu_761_p2() {
    isneg_not_fu_761_p2 = (isneg_2_reg_1341.read() ^ ap_const_lv1_1);
}

void Compult::thread_newsignbit_0_not_i_fu_1075_p2() {
    newsignbit_0_not_i_fu_1075_p2 = (newsignbit_5_fu_1045_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_newsignbit_0_not_i_i_fu_617_p2() {
    newsignbit_0_not_i_i_fu_617_p2 = (newsignbit_2_fu_575_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_newsignbit_2_fu_575_p3() {
    newsignbit_2_fu_575_p3 = p_Val2_17_fu_557_p2.read().range(29, 29);
}

void Compult::thread_newsignbit_4_fu_895_p3() {
    newsignbit_4_fu_895_p3 = p_Val2_26_fu_890_p2.read().range(15, 15);
}

void Compult::thread_newsignbit_5_fu_1045_p3() {
    newsignbit_5_fu_1045_p3 = u_out_V_fu_1026_p3.read().range(2, 2);
}

void Compult::thread_overflow_2_fu_611_p2() {
    overflow_2_fu_611_p2 = (brmerge_i6_i_fu_599_p2.read() & tmp_37_i6_fu_605_p2.read());
}

void Compult::thread_overflow_3_fu_971_p2() {
    overflow_3_fu_971_p2 = (brmerge_i7_fu_961_p2.read() & tmp_11_fu_966_p2.read());
}

void Compult::thread_overflow_4_fu_1105_p2() {
    overflow_4_fu_1105_p2 = (brmerge_i8_reg_1473.read() & tmp_12_fu_1100_p2.read());
}

void Compult::thread_overflow_fu_472_p2() {
    overflow_fu_472_p2 = (brmerge_i_i2_reg_1274.read() & tmp_34_i_fu_467_p2.read());
}

void Compult::thread_p_38_i_fu_950_p2() {
    p_38_i_fu_950_p2 = (carry_fu_909_p2.read() & Range1_all_ones_fu_914_p2.read());
}

void Compult::thread_p_41_i_fu_937_p2() {
    p_41_i_fu_937_p2 = (signbit_1_reg_1371.read() & tmp_10_fu_932_p2.read());
}

void Compult::thread_p_Result_21_i_fu_583_p4() {
    p_Result_21_i_fu_583_p4 = p_Val2_17_fu_557_p2.read().range(32, 30);
}

void Compult::thread_p_Result_s_fu_1053_p4() {
    p_Result_s_fu_1053_p4 = u_out_V_fu_1026_p3.read().range(15, 3);
}

void Compult::thread_p_Val2_101_mux_i_fu_671_p3() {
    p_Val2_101_mux_i_fu_671_p3 = (!brmerge_i_i5_i_fu_657_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i5_i_fu_657_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_18_reg_1296.read());
}

void Compult::thread_p_Val2_10_fu_525_p2() {
    p_Val2_10_fu_525_p2 = (!p_Val2_9_reg_1244.read().is_01() || !tmp_3_fu_522_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_Val2_9_reg_1244.read()) + sc_biguint<16>(tmp_3_fu_522_p1.read()));
}

void Compult::thread_p_Val2_115_mux_fu_771_p3() {
    p_Val2_115_mux_fu_771_p3 = (!brmerge_i_i_fu_757_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i_fu_757_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_23_reg_1348.read());
}

void Compult::thread_p_Val2_118_mux_fu_1014_p3() {
    p_Val2_118_mux_fu_1014_p3 = (!brmerge_i_i6_reg_1452.read()[0].is_01())? sc_lv<16>(): ((brmerge_i_i6_reg_1452.read()[0].to_bool())? ap_const_lv16_7FFF: p_Val2_26_reg_1419.read());
}

void Compult::thread_p_Val2_11_fu_274_p3() {
    p_Val2_11_fu_274_p3 = esl_concat<16,12>(tmp_15_reg_1186.read(), ap_const_lv12_0);
}

void Compult::thread_p_Val2_120_mux_fu_1132_p3() {
    p_Val2_120_mux_fu_1132_p3 = (!brmerge_i_i7_fu_1114_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_i_i7_fu_1114_p2.read()[0].to_bool())? ap_const_lv30_1FFFFFFF: p_Val2_28_fu_1093_p3.read());
}

void Compult::thread_p_Val2_12_fu_293_p2() {
    p_Val2_12_fu_293_p2 = (!tmp_i_cast_fu_281_p1.read().is_01() || !tmp_i_cast_36_fu_289_p1.read().is_01())? sc_lv<29>(): (sc_biguint<29>(tmp_i_cast_fu_281_p1.read()) - sc_biguint<29>(tmp_i_cast_36_fu_289_p1.read()));
}

void Compult::thread_p_Val2_14_fu_461_p3() {
    p_Val2_14_fu_461_p3 = esl_concat<31,1>(tmp_s_reg_1233.read(), qb_assign_5_reg_1269.read());
}

void Compult::thread_p_Val2_15_fu_514_p3() {
    p_Val2_15_fu_514_p3 = (!tmp7_fu_493_p2.read()[0].is_01())? sc_lv<32>(): ((tmp7_fu_493_p2.read()[0].to_bool())? p_Val2_97_mux_i_fu_498_p3.read(): p_Val2_i4_fu_506_p3.read());
}

void Compult::thread_p_Val2_17_fu_557_p2() {
    p_Val2_17_fu_557_p2 = (!tmp_35_i_fu_546_p1.read().is_01() || !tmp_36_i5_fu_553_p1.read().is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_35_i_fu_546_p1.read()) - sc_bigint<33>(tmp_36_i5_fu_553_p1.read()));
}

void Compult::thread_p_Val2_18_fu_571_p1() {
    p_Val2_18_fu_571_p1 = p_Val2_17_fu_557_p2.read().range(30-1, 0);
}

void Compult::thread_p_Val2_21_fu_706_p3() {
    p_Val2_21_fu_706_p3 = esl_concat<27,2>(grp_Compult_mpc_pso_fu_161_ap_return.read(), ap_const_lv2_0);
}

void Compult::thread_p_Val2_22_fu_721_p2() {
    p_Val2_22_fu_721_p2 = (!tmp_4_fu_714_p1.read().is_01() || !tmp_5_fu_717_p1.read().is_01())? sc_lv<31>(): (sc_bigint<31>(tmp_4_fu_714_p1.read()) + sc_bigint<31>(tmp_5_fu_717_p1.read()));
}

void Compult::thread_p_Val2_23_fu_735_p1() {
    p_Val2_23_fu_735_p1 = p_Val2_22_fu_721_p2.read().range(30-1, 0);
}

void Compult::thread_p_Val2_26_fu_890_p2() {
    p_Val2_26_fu_890_p2 = (!p_Val2_25_reg_1378.read().is_01() || !tmp_9_fu_887_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_Val2_25_reg_1378.read()) + sc_biguint<16>(tmp_9_fu_887_p1.read()));
}

void Compult::thread_p_Val2_28_fu_1093_p3() {
    p_Val2_28_fu_1093_p3 = esl_concat<3,27>(tmp_53_reg_1468.read(), ap_const_lv27_0);
}

void Compult::thread_p_Val2_3_i_fu_678_p3() {
    p_Val2_3_i_fu_678_p3 = (!underflow_2_reg_1308.read()[0].is_01())? sc_lv<30>(): ((underflow_2_reg_1308.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_18_reg_1296.read());
}

void Compult::thread_p_Val2_4_fu_1020_p3() {
    p_Val2_4_fu_1020_p3 = (!underflow_4_reg_1447.read()[0].is_01())? sc_lv<16>(): ((underflow_4_reg_1447.read()[0].to_bool())? ap_const_lv16_8000: p_Val2_26_reg_1419.read());
}

void Compult::thread_p_Val2_5_fu_1140_p3() {
    p_Val2_5_fu_1140_p3 = (!underflow_5_fu_1110_p2.read()[0].is_01())? sc_lv<30>(): ((underflow_5_fu_1110_p2.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_28_fu_1093_p3.read());
}

void Compult::thread_p_Val2_7_fu_246_p2() {
    p_Val2_7_fu_246_p2 = (!p_Val2_6_reg_1156.read().is_01() || !tmp_1_fu_243_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_Val2_6_reg_1156.read()) + sc_biguint<16>(tmp_1_fu_243_p1.read()));
}

void Compult::thread_p_Val2_8_fu_378_p0() {
    p_Val2_8_fu_378_p0 =  (sc_lv<16>) (p_Val2_8_fu_378_p00.read());
}

void Compult::thread_p_Val2_8_fu_378_p00() {
    p_Val2_8_fu_378_p00 = esl_zext<36,16>(ref_in_V.read());
}

void Compult::thread_p_Val2_8_fu_378_p2() {
    p_Val2_8_fu_378_p2 = (!p_Val2_8_fu_378_p0.read().is_01() || !ap_const_lv36_73333.is_01())? sc_lv<36>(): sc_biguint<16>(p_Val2_8_fu_378_p0.read()) * sc_biguint<36>(ap_const_lv36_73333);
}

void Compult::thread_p_Val2_97_mux_i_fu_498_p3() {
    p_Val2_97_mux_i_fu_498_p3 = (!brmerge_i_i_i3_fu_487_p2.read()[0].is_01())? sc_lv<32>(): ((brmerge_i_i_i3_fu_487_p2.read()[0].to_bool())? ap_const_lv32_7FFFFFFF: p_Val2_14_fu_461_p3.read());
}

void Compult::thread_p_Val2_i4_fu_506_p3() {
    p_Val2_i4_fu_506_p3 = (!underflow_fu_482_p2.read()[0].is_01())? sc_lv<32>(): ((underflow_fu_482_p2.read()[0].to_bool())? ap_const_lv32_80000000: p_Val2_14_fu_461_p3.read());
}

void Compult::thread_p_Val2_s_37_fu_778_p3() {
    p_Val2_s_37_fu_778_p3 = (!underflow_3_fu_752_p2.read()[0].is_01())? sc_lv<30>(): ((underflow_3_fu_752_p2.read()[0].to_bool())? ap_const_lv30_20000000: p_Val2_23_reg_1348.read());
}

void Compult::thread_p_Val2_s_fu_184_p0() {
    p_Val2_s_fu_184_p0 =  (sc_lv<16>) (p_Val2_s_fu_184_p00.read());
}

void Compult::thread_p_Val2_s_fu_184_p00() {
    p_Val2_s_fu_184_p00 = esl_zext<36,16>(y_in_V.read());
}

void Compult::thread_p_Val2_s_fu_184_p2() {
    p_Val2_s_fu_184_p2 = (!p_Val2_s_fu_184_p0.read().is_01() || !ap_const_lv36_73333.is_01())? sc_lv<36>(): sc_biguint<16>(p_Val2_s_fu_184_p0.read()) * sc_biguint<36>(ap_const_lv36_73333);
}

void Compult::thread_p_not38_i_fu_1081_p2() {
    p_not38_i_fu_1081_p2 = (!p_Result_s_fu_1053_p4.read().is_01() || !ap_const_lv13_1FFF.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_s_fu_1053_p4.read() != ap_const_lv13_1FFF);
}

void Compult::thread_p_not38_i_i_fu_623_p2() {
    p_not38_i_i_fu_623_p2 = (!p_Result_21_i_fu_583_p4.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_21_i_fu_583_p4.read() != ap_const_lv3_7);
}

void Compult::thread_p_not_i5_i_fu_593_p2() {
    p_not_i5_i_fu_593_p2 = (!p_Result_21_i_fu_583_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_21_i_fu_583_p4.read() != ap_const_lv3_0);
}

void Compult::thread_p_not_i6_fu_1063_p2() {
    p_not_i6_fu_1063_p2 = (!p_Result_s_fu_1053_p4.read().is_01() || !ap_const_lv13_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_s_fu_1053_p4.read() != ap_const_lv13_0);
}

void Compult::thread_p_not_i_fu_956_p2() {
    p_not_i_fu_956_p2 = (deleted_zeros_reg_1431.read() ^ ap_const_lv1_1);
}

void Compult::thread_p_not_i_i_fu_431_p2() {
    p_not_i_i_fu_431_p2 = (!tmp_38_reg_1238.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_38_reg_1238.read() != ap_const_lv7_0);
}

void Compult::thread_phitmp8_fu_538_p3() {
    phitmp8_fu_538_p3 = (!tmp_33_fu_530_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_33_fu_530_p3.read()[0].to_bool())? p_Val2_10_fu_525_p2.read(): ap_const_lv16_FFFF);
}

void Compult::thread_phitmp_fu_259_p3() {
    phitmp_fu_259_p3 = (!tmp_28_fu_251_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_28_fu_251_p3.read()[0].to_bool())? p_Val2_7_fu_246_p2.read(): ap_const_lv16_FFFF);
}

void Compult::thread_qb_assign_1_fu_238_p2() {
    qb_assign_1_fu_238_p2 = (r_i_i_fu_233_p2.read() & qbit_reg_1161.read());
}

void Compult::thread_qb_assign_3_fu_456_p2() {
    qb_assign_3_fu_456_p2 = (r_i_i2_fu_451_p2.read() & qbit_1_reg_1249.read());
}

void Compult::thread_qb_assign_5_fu_422_p2() {
    qb_assign_5_fu_422_p2 = (tmp_37_reg_1228.read() & qbit_2_reg_1217.read());
}

void Compult::thread_qb_assign_7_fu_882_p2() {
    qb_assign_7_fu_882_p2 = (r_i_i3_fu_877_p2.read() & qbit_3_reg_1383.read());
}

void Compult::thread_r_1_fu_446_p2() {
    r_1_fu_446_p2 = (!tmp_30_reg_1254.read().is_01() || !ap_const_lv18_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1254.read() != ap_const_lv18_0);
}

void Compult::thread_r_2_fu_872_p2() {
    r_2_fu_872_p2 = (!tmp_47_reg_1388.read().is_01() || !ap_const_lv36_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_47_reg_1388.read() != ap_const_lv36_0);
}

void Compult::thread_r_fu_228_p2() {
    r_fu_228_p2 = (!tmp_25_reg_1166.read().is_01() || !ap_const_lv18_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_25_reg_1166.read() != ap_const_lv18_0);
}

void Compult::thread_r_i_i2_fu_451_p2() {
    r_i_i2_fu_451_p2 = (tmp_32_reg_1264.read() | r_1_fu_446_p2.read());
}

void Compult::thread_r_i_i3_fu_877_p2() {
    r_i_i3_fu_877_p2 = (tmp_49_reg_1398.read() | r_2_fu_872_p2.read());
}

void Compult::thread_r_i_i_fu_233_p2() {
    r_i_i_fu_233_p2 = (tmp_27_reg_1176.read() | r_fu_228_p2.read());
}

void Compult::thread_this_assign_s_fu_698_p3() {
    this_assign_s_fu_698_p3 = esl_concat<16,12>(tmp_17_reg_1315.read(), ap_const_lv12_0);
}

void Compult::thread_tmp7_fu_493_p2() {
    tmp7_fu_493_p2 = (brmerge40_demorgan_i_i_reg_1279.read() | tmp_34_i_fu_467_p2.read());
}

void Compult::thread_tmp8_demorgan_fu_981_p2() {
    tmp8_demorgan_fu_981_p2 = (p_38_i_reg_1441.read() | brmerge40_demorgan_i_fu_977_p2.read());
}

void Compult::thread_tmp8_fu_986_p2() {
    tmp8_fu_986_p2 = (tmp8_demorgan_fu_981_p2.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp9_fu_1003_p2() {
    tmp9_fu_1003_p2 = (brmerge40_demorgan_i_fu_977_p2.read() | tmp_11_fu_966_p2.read());
}

void Compult::thread_tmp_10_fu_932_p2() {
    tmp_10_fu_932_p2 = (tmp_51_reg_1403.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_11_fu_966_p2() {
    tmp_11_fu_966_p2 = (signbit_1_reg_1371.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_12_fu_1100_p2() {
    tmp_12_fu_1100_p2 = (isneg_3_reg_1462.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_15_fu_267_p3() {
    tmp_15_fu_267_p3 = (!tmp_26_reg_1171.read()[0].is_01())? sc_lv<16>(): ((tmp_26_reg_1171.read()[0].to_bool())? phitmp_fu_259_p3.read(): p_Val2_7_fu_246_p2.read());
}

void Compult::thread_tmp_16_fu_305_p3() {
    tmp_16_fu_305_p3 = esl_concat<29,2>(p_Val2_12_reg_1196.read(), ap_const_lv2_0);
}

void Compult::thread_tmp_17_fu_646_p3() {
    tmp_17_fu_646_p3 = (!tmp_31_reg_1259.read()[0].is_01())? sc_lv<16>(): ((tmp_31_reg_1259.read()[0].to_bool())? phitmp8_fu_538_p3.read(): p_Val2_10_fu_525_p2.read());
}

void Compult::thread_tmp_1_fu_243_p1() {
    tmp_1_fu_243_p1 = esl_zext<16,1>(qb_assign_1_reg_1181.read());
}

void Compult::thread_tmp_25_fu_208_p1() {
    tmp_25_fu_208_p1 = p_Val2_s_fu_184_p2.read().range(18-1, 0);
}

void Compult::thread_tmp_28_fu_251_p3() {
    tmp_28_fu_251_p3 = p_Val2_7_fu_246_p2.read().range(15, 15);
}

void Compult::thread_tmp_2_fu_903_p2() {
    tmp_2_fu_903_p2 = (newsignbit_4_fu_895_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_30_fu_402_p1() {
    tmp_30_fu_402_p1 = p_Val2_8_fu_378_p2.read().range(18-1, 0);
}

void Compult::thread_tmp_33_fu_530_p3() {
    tmp_33_fu_530_p3 = p_Val2_10_fu_525_p2.read().range(15, 15);
}

void Compult::thread_tmp_34_i_fu_467_p2() {
    tmp_34_i_fu_467_p2 = (signbit_reg_1211.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_35_i_fu_546_p1() {
    tmp_35_i_fu_546_p1 = esl_sext<33,32>(p_Val2_15_reg_1290.read());
}

void Compult::thread_tmp_36_i5_fu_553_p1() {
    tmp_36_i5_fu_553_p1 = esl_sext<33,32>(x2_2_V.read());
}

void Compult::thread_tmp_37_i6_fu_605_p2() {
    tmp_37_i6_fu_605_p2 = (isneg_fu_563_p3.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_3_fu_522_p1() {
    tmp_3_fu_522_p1 = esl_zext<16,1>(qb_assign_3_reg_1285.read());
}

void Compult::thread_tmp_47_fu_834_p1() {
    tmp_47_fu_834_p1 = grp_fu_802_p2.read().range(36-1, 0);
}

void Compult::thread_tmp_4_fu_714_p1() {
    tmp_4_fu_714_p1 = esl_sext<31,30>(u_V.read());
}

void Compult::thread_tmp_53_fu_1041_p1() {
    tmp_53_fu_1041_p1 = u_out_V_fu_1026_p3.read().range(3-1, 0);
}

void Compult::thread_tmp_5_fu_717_p1() {
    tmp_5_fu_717_p1 = esl_sext<31,29>(p_Val2_21_fu_706_p3.read());
}

void Compult::thread_tmp_6_fu_747_p2() {
    tmp_6_fu_747_p2 = (newsignbit_3_reg_1354.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_7_fu_785_p3() {
    tmp_7_fu_785_p3 = (!brmerge_fu_766_p2.read()[0].is_01())? sc_lv<30>(): ((brmerge_fu_766_p2.read()[0].to_bool())? p_Val2_115_mux_fu_771_p3.read(): p_Val2_s_37_fu_778_p3.read());
}

void Compult::thread_tmp_9_fu_887_p1() {
    tmp_9_fu_887_p1 = esl_zext<16,1>(qb_assign_7_reg_1414.read());
}

void Compult::thread_tmp_fu_477_p2() {
    tmp_fu_477_p2 = (brmerge40_demorgan_i_i_reg_1279.read() ^ ap_const_lv1_1);
}

void Compult::thread_tmp_i_cast_36_fu_289_p1() {
    tmp_i_cast_36_fu_289_p1 = esl_zext<29,28>(x1_1_V.read());
}

void Compult::thread_tmp_i_cast_fu_281_p1() {
    tmp_i_cast_fu_281_p1 = esl_zext<29,28>(p_Val2_11_fu_274_p3.read());
}

void Compult::thread_u_out_V_fu_1026_p3() {
    u_out_V_fu_1026_p3 = (!underflow_17_not_reg_1457.read()[0].is_01())? sc_lv<16>(): ((underflow_17_not_reg_1457.read()[0].to_bool())? p_Val2_118_mux_fu_1014_p3.read(): p_Val2_4_fu_1020_p3.read());
}

void Compult::thread_underflow_16_not_i_fu_661_p2() {
    underflow_16_not_i_fu_661_p2 = (underflow_2_reg_1308.read() ^ ap_const_lv1_1);
}

void Compult::thread_underflow_17_not_fu_1009_p2() {
    underflow_17_not_fu_1009_p2 = (tmp9_fu_1003_p2.read() | p_38_i_reg_1441.read());
}

void Compult::thread_underflow_18_not_fu_1120_p2() {
    underflow_18_not_fu_1120_p2 = (underflow_5_fu_1110_p2.read() ^ ap_const_lv1_1);
}

void Compult::thread_underflow_2_fu_635_p2() {
    underflow_2_fu_635_p2 = (brmerge39_i_i_fu_629_p2.read() & isneg_fu_563_p3.read());
}

void Compult::thread_underflow_3_fu_752_p2() {
    underflow_3_fu_752_p2 = (isneg_2_reg_1341.read() & tmp_6_fu_747_p2.read());
}

void Compult::thread_underflow_4_fu_992_p2() {
    underflow_4_fu_992_p2 = (signbit_1_reg_1371.read() & tmp8_fu_986_p2.read());
}

void Compult::thread_underflow_5_fu_1110_p2() {
    underflow_5_fu_1110_p2 = (brmerge39_i_reg_1478.read() & isneg_3_reg_1462.read());
}

void Compult::thread_underflow_fu_482_p2() {
    underflow_fu_482_p2 = (signbit_reg_1211.read() & tmp_fu_477_p2.read());
}

void Compult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_Compult_mpc_pso_fu_161_ap_done.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void Compult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y_in_V\" :  \"" << y_in_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ref_in_V\" :  \"" << ref_in_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

